import { useState, type FormEvent } from 'react'
import type { DashboardData, IssuedApiToken, Language } from '../types'
import type { ControlApi } from '../api/controlApi'
import { PageHeader } from '../components/AppShell'
import { Icon } from '../components/Icon'
import { Field, Modal, SecretResult } from '../components/Modal'
import { Badge, ConfirmButton, Empty, ErrorBanner, Panel } from '../components/UI'
import { date, short } from '../lib/format'

export function Access({ language, data, api, onChanged }: { language: Language; data: DashboardData; api: ControlApi; onChanged: () => Promise<unknown> | void }) {
  const [issue, setIssue] = useState(false)
  const [issued, setIssued] = useState<IssuedApiToken>()
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string>()
  async function action(run: () => Promise<unknown>) { setBusy(true); setError(undefined); try { await run(); await onChanged() } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } finally { setBusy(false) } }
  return <><PageHeader language={language} section="access"/>{error ? <ErrorBanner onClose={() => setError(undefined)}>{error}</ErrorBanner> : null}<Panel title="API tokens" meta="ADMIN access required" action={<button className="button secondary" type="button" onClick={() => setIssue(true)}><Icon name="plus" size={15}/> Issue token</button>}>{data.tokens.length ? <div className="table-scroll"><table><thead><tr><th>Name</th><th>Role</th><th>Created</th><th>Expires</th><th>Last used</th><th/></tr></thead><tbody>{data.tokens.map(token => <tr key={token.id}><td><strong>{token.name}</strong><small>{short(token.id)}</small></td><td><span className={`role-chip ${token.role.toLowerCase()}`}>{token.role}</span></td><td className="mono">{date(token.createdAt)}</td><td className="mono">{date(token.expiresAt)}</td><td className="mono">{date(token.lastUsedAt)}</td><td className="row-actions">{!token.revokedAt ? <ConfirmButton onConfirm={() => void action(() => api.revokeToken(token.id))}>Revoke</ConfirmButton> : <Badge tone="bad">revoked</Badge>}</td></tr>)}</tbody></table></div> : <Empty title="No token inventory" text="A VIEWER or OPERATOR token cannot list ADMIN resources."/>}</Panel><Panel title="Node certificates" meta="Certificate private keys never leave nodes" className="section-gap">{data.certificates.length ? <div className="table-scroll"><table><thead><tr><th>Node</th><th>Serial</th><th>Fingerprint</th><th>Expires</th><th>State</th><th/></tr></thead><tbody>{data.certificates.map(cert => <tr key={cert.serialNumber}><td>{cert.nodeId}</td><td className="mono">{cert.serialNumber}</td><td className="mono">{short(cert.fingerprintSha256, 28)}</td><td className="mono">{date(cert.expiresAt)}</td><td><Badge tone={cert.revokedAt ? 'bad' : 'ok'}>{cert.revokedAt ? 'revoked' : 'valid'}</Badge></td><td className="row-actions">{!cert.revokedAt ? <ConfirmButton onConfirm={() => void action(() => api.revokeCertificate(cert.nodeId, cert.serialNumber, 'Revoked from access inventory'))}>Revoke</ConfirmButton> : null}</td></tr>)}</tbody></table></div> : <Empty title="No certificates for selected node"/>}</Panel>
    {issue ? <Modal title="Issue API token" hint="The plaintext token is shown exactly once; only its SHA-256 hash is persisted." busy={busy} submitLabel={issued ? undefined : 'Issue token'} onClose={() => { setIssue(false); setIssued(undefined) }} onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void action(async () => { const result = await api.issueToken({ name: String(form.get('name')), role: String(form.get('role')), ttlSeconds: form.get('ttl') ? Number(form.get('ttl')) : null }); setIssued(result) }) }}>{issued ? <SecretResult label="API token" value={issued.secret}/> : <><Field label="Name"><input required name="name" placeholder="deploy-bot"/></Field><Field label="Role"><select name="role" defaultValue="VIEWER"><option>VIEWER</option><option>OPERATOR</option><option>ADMIN</option></select></Field><Field label="TTL, seconds" hint="Leave empty for no expiry"><input name="ttl" type="number" min="60"/></Field></>}</Modal> : null}
  </>
}
