import { useDeferredValue, useState, type FormEvent } from 'react'
import type { BoardResource, DashboardData, Language } from '../types'
import type { ControlApi } from '../api/controlApi'
import { PageHeader } from '../components/AppShell'
import { Icon } from '../components/Icon'
import { Field, Modal } from '../components/Modal'
import { Badge, ConfirmButton, Empty, ErrorBanner } from '../components/UI'
import { short } from '../lib/format'

export function Boards({ language, data, search, api, onChanged }: { language: Language; data: DashboardData; search: string; api: ControlApi; onChanged: () => Promise<unknown> | void }) {
  const query = useDeferredValue(search.toLowerCase())
  const catalog = data.catalog
  const runtime = catalog ? data.runtimes[catalog.node.id] : undefined
  const boards = (catalog?.boards ?? []).filter(board => `${board.name} ${board.id} ${board.hash}`.toLowerCase().includes(query))
  const [create, setCreate] = useState(false)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string>()
  async function action(run: () => Promise<unknown>) { setBusy(true); setError(undefined); try { await run(); await onChanged() } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } finally { setBusy(false) } }
  return <><PageHeader language={language} section="boards" action={<button className="button primary" type="button" disabled={!catalog} onClick={() => setCreate(true)}><Icon name="plus" size={15}/> Add board</button>}/>{error ? <ErrorBanner onClose={() => setError(undefined)}>{error}</ErrorBanner> : null}<div className="board-grid">{boards.length ? boards.map(board => { const fact = runtime?.boards.find(item => item.boardTag === board.id); const assigned = catalog!.assignment.boardIds.includes(board.id); const assignedUsers = catalog!.assignment.users.filter(user => user.boardIds.includes(board.id)); const canRemove = !assigned || (catalog!.assignment.boardIds.length > 1 && assignedUsers.length === 0); return <article className="board-card" key={board.id}><header><div><span className={`dot ${fact?.error ? 'warn' : board.state === 'enabled' ? 'ok' : board.state === 'revoked' ? 'bad' : 'neutral'}`}/><h2>{board.name}</h2><code>{board.id}</code></div><Badge tone={fact?.error ? 'warn' : fact?.state === 'running' ? 'ok' : board.state === 'revoked' ? 'bad' : 'info'}>{fact?.state ?? board.state}</Badge></header><p className="board-hash">sha256:{short(board.hash, 30)}</p>{fact?.error ? <p className="board-error">{fact.error}</p> : null}<dl><div><dt>Lanes</dt><dd>{board.maxLanes}</dd></div><div><dt>Sessions</dt><dd>{runtime?.sessions.filter(session => session.boardTag === board.id).length ?? 0}</dd></div><div><dt>Revision</dt><dd>{board.version}</dd></div><div><dt>Node</dt><dd>{catalog!.node.id}</dd></div></dl><footer>{board.state !== 'revoked' ? <button type="button" onClick={() => void action(() => api.putBoard(catalog!.node.id, board.id, catalog!.version, boardBody(board, board.state === 'enabled' ? 'disabled' : 'enabled')))}>{board.state === 'enabled' ? 'Disable' : 'Enable'}</button> : null}{canRemove ? <ConfirmButton onConfirm={() => void action(async () => { if (!assigned) { await api.removeBoard(catalog!.node.id, board.id, catalog!.version); return } const assignment = await api.replaceAssignment(catalog!.node.id, catalog!.version, { boardIds: catalog!.assignment.boardIds.filter(id => id !== board.id), users: catalog!.assignment.users }); await api.removeBoard(catalog!.node.id, board.id, assignment.catalog.version) })}>Remove</ConfirmButton> : null}</footer></article> }) : <div className="span-all"><Empty title="No boards on selected node"/></div>}</div>
    {create && catalog ? <Modal title="Add board" hint="Новая доска автоматически добавится в assignment выбранной ноды." busy={busy} submitLabel="Add board" onClose={() => setCreate(false)} onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void action(async () => { const boardId = String(form.get('id')); const created = await api.putBoard(catalog.node.id, boardId, catalog.version, { name: String(form.get('name')), hash: String(form.get('hash')), hubSlide: String(form.get('hubSlide')) || null, apiBase: String(form.get('apiBase')) || null, guestName: String(form.get('guestName')) || null, state: 'enabled', maxLanes: Number(form.get('maxLanes')) }); const boardIds = catalog.assignment.boardIds.includes(boardId) ? catalog.assignment.boardIds : [...catalog.assignment.boardIds, boardId]; await api.replaceAssignment(catalog.node.id, created.catalog.version, { boardIds, users: catalog.assignment.users }); setCreate(false) }) }}><Field label="ID"><input required name="id" pattern="[A-Za-z0-9][A-Za-z0-9._]*(?:-[A-Za-z0-9._]+)*" placeholder="primary"/></Field><Field label="Name"><input required name="name" placeholder="Primary board"/></Field><Field label="Board hash"><input required name="hash" placeholder="Board connection hash"/></Field><Field label="Hub slide"><input name="hubSlide"/></Field><Field label="API base"><input name="apiBase"/></Field><Field label="Guest name"><input name="guestName"/></Field><Field label="Max lanes"><input required type="number" min="1" max="32" name="maxLanes" defaultValue="2"/></Field></Modal> : null}
  </>
}
function boardBody(board: BoardResource, state: string) { return { name: board.name, hash: board.hash, hubSlide: board.hubSlide ?? null, apiBase: board.apiBase ?? null, guestName: board.guestName ?? null, state, maxLanes: board.maxLanes } }
