import { useDeferredValue, useState, type FormEvent } from 'react'
import type { DashboardData, IssuedSubscription, Language, Subscription } from '../types'
import type { ControlApi } from '../api/controlApi'
import { PageHeader } from '../components/AppShell'
import { Icon } from '../components/Icon'
import { Field, Modal, SecretResult } from '../components/Modal'
import { Badge, Empty, ErrorBanner, Panel } from '../components/UI'
import { date, short } from '../lib/format'

export function Subscriptions({ language, data, search, api, onChanged }: { language: Language; data: DashboardData; search: string; api: ControlApi; onChanged: () => Promise<unknown> | void }) {
  const query = useDeferredValue(search.toLowerCase())
  const rows = data.subscriptions.filter(item => `${item.name} ${item.id} ${item.keys.map(key => key.userId).join(' ')}`.toLowerCase().includes(query))
  const [create, setCreate] = useState(false)
  const [selected, setSelected] = useState<Subscription>()
  const [issued, setIssued] = useState<IssuedSubscription>()
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string>()
  async function action(run: () => Promise<unknown>) { setBusy(true); setError(undefined); try { await run(); await onChanged() } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } finally { setBusy(false) } }
  const active = data.subscriptions.filter(item => item.state === 'enabled').length
  return <><PageHeader language={language} section="subscriptions" action={<button className="button primary" type="button" disabled={!data.catalog?.users.length} onClick={() => setCreate(true)}><Icon name="plus" size={15}/> New subscription</button>}/>
    {error ? <ErrorBanner onClose={() => setError(undefined)}>{error}</ErrorBanner> : null}
    <div className="sub-kpis"><div><span>Active</span><strong className="ok">{active}</strong></div><div><span>Disabled</span><strong>{data.subscriptions.filter(item => item.state === 'disabled').length}</strong></div><div><span>Revoked</span><strong className="bad">{data.subscriptions.filter(item => item.state === 'revoked').length}</strong></div><div><span>Total keys</span><strong>{data.subscriptions.reduce((sum, item) => sum + item.keys.length, 0)}</strong></div></div>
    <Panel>{rows.length ? <div className="table-scroll"><table><thead><tr><th>Subscription</th><th>Users</th><th>Nodes</th><th>State</th><th>Revision</th><th>Updated</th><th/></tr></thead><tbody>{rows.map(item => <tr className="clickable" key={item.id} onClick={() => setSelected(item)}><td><strong>{item.name}</strong><small>{item.id}</small></td><td>{[...new Set(item.keys.map(key => key.userId))].join(', ') || '—'}</td><td>{[...new Set(item.keys.map(key => key.nodeId))].map(node => <span className="node-tag" key={node}>{node}</span>)}</td><td><Badge tone={item.state === 'enabled' ? 'ok' : item.state === 'revoked' ? 'bad' : 'neutral'}>{item.state}</Badge></td><td className="mono">{item.version}</td><td className="mono">{date(item.updatedAt)}</td><td><Icon name="chevron" size={14}/></td></tr>)}</tbody></table></div> : <Empty title="No subscriptions" text="Create the first stable delivery identity for a user."/>}</Panel>
    {create ? <Modal title="New subscription" hint="The recovery private key and token are shown exactly once." busy={busy} submitLabel="Create subscription" onClose={() => { setCreate(false); setIssued(undefined) }} onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void action(async () => { const nodeId = String(form.get('nodeId')); const userId = String(form.get('userId')); const result = await api.createSubscription({ name: String(form.get('name')), keys: [{ id: String(form.get('keyId')), name: String(form.get('keyName')), nodeId, userId }] }); setIssued(result) }) }}>
      {issued ? <><SecretResult label="Subscription token" value={issued.token}/><SecretResult label="Recovery client private key" value={issued.recoveryClientPrivateKey}/></> : <><Field label="Name"><input required name="name" placeholder="Alice — phone"/></Field><Field label="Node"><select required name="nodeId" defaultValue={data.catalog?.node.id}>{data.catalog ? <option value={data.catalog.node.id}>{data.catalog.node.name}</option> : null}</select></Field><Field label="User"><select required name="userId">{data.catalog?.users.map(user => <option key={user.id} value={user.id}>{user.name} · {user.id}</option>)}</select></Field><Field label="Key ID"><input required name="keyId" placeholder="alice-phone"/></Field><Field label="Key name"><input required name="keyName" placeholder="Phone"/></Field></>}
    </Modal> : null}
    {selected ? <SubscriptionDrawer subscription={selected} busy={busy} onClose={() => setSelected(undefined)} onState={state => void action(async () => { const updated = await api.replaceSubscription(selected, state); setSelected(updated) })}/> : null}
  </>
}

function SubscriptionDrawer({ subscription, busy, onClose, onState }: { subscription: Subscription; busy: boolean; onClose: () => void; onState: (state: string) => void }) {
  return <div className="drawer-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><aside className="drawer"><header className="drawer-header"><div><span className={`dot ${subscription.state === 'enabled' ? 'ok' : subscription.state === 'revoked' ? 'bad' : 'neutral'}`}/><h2>{subscription.name}</h2><Badge tone={subscription.state === 'enabled' ? 'ok' : subscription.state === 'revoked' ? 'bad' : 'neutral'}>{subscription.state}</Badge><p>{subscription.id} · revision {subscription.version}</p></div><button className="icon-button" type="button" onClick={onClose}><Icon name="close"/></button></header><div className="drawer-body"><div className="detail-metrics"><div><span>Keys</span><strong>{subscription.keys.length}</strong></div><div><span>Created</span><strong>{date(subscription.createdAt)}</strong></div><div><span>Updated</span><strong>{date(subscription.updatedAt)}</strong></div><div><span>Recovery key</span><strong>{short(subscription.recoveryClientPublicKey)}</strong></div></div><h3>Attached keys</h3><div className="compact-list">{subscription.keys.map(key => <div key={key.id}><strong>{key.name}</strong><code>{key.id}</code><span>{key.userId}</span><span className="node-tag">{key.nodeId}</span></div>)}</div><div className="drawer-actions">{subscription.state !== 'revoked' ? <button disabled={busy} className="button secondary" type="button" onClick={() => onState(subscription.state === 'enabled' ? 'disabled' : 'enabled')}>{subscription.state === 'enabled' ? 'Disable' : 'Enable'}</button> : null}{subscription.state !== 'revoked' ? <button disabled={busy} className="button danger" type="button" onClick={() => { if (window.confirm('Revoke this subscription permanently?')) onState('revoked') }}>Revoke</button> : null}</div><p className="form-note">Existing subscription tokens and recovery private keys are intentionally not returned by the API.</p></div></aside></div>
}
