import { useState, type FormEvent } from 'react'
import type { DashboardData, Language, TrafficQuotaUsage } from '../types'
import type { ControlApi } from '../api/controlApi'
import { PageHeader } from '../components/AppShell'
import { TrafficChart, Progress } from '../components/Charts'
import { Field, Modal } from '../components/Modal'
import { Icon } from '../components/Icon'
import { ConfirmButton, Empty, ErrorBanner, Panel } from '../components/UI'
import { bytes } from '../lib/format'

export function Traffic({ language, data, api, onChanged }: { language: Language; data: DashboardData; api: ControlApi; onChanged: () => Promise<unknown> | void }) {
  const [quota, setQuota] = useState<TrafficQuotaUsage | 'new'>()
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string>()
  const nodeId = data.catalog?.node.id
  const totalInterface = data.interfaceTotals.reduce((sum, item) => sum + item.rxBytes + item.txBytes, 0)
  const totalPayload = data.userTotals.reduce((sum, item) => sum + item.rxBytes + item.txBytes, 0)
  const topUsers = [...data.userTotals].sort((a, b) => b.rxBytes + b.txBytes - a.rxBytes - a.txBytes)
  async function action(run: () => Promise<unknown>) { setBusy(true); setError(undefined); try { await run(); await onChanged() } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } finally { setBusy(false) } }
  return <><PageHeader language={language} section="traffic"/>{error ? <ErrorBanner onClose={() => setError(undefined)}>{error}</ErrorBanner> : null}<div className="traffic-totals"><div><span>Interface transfer</span><strong>{bytes(totalInterface)}</strong><small>rx + tx</small></div><div><span>User payload</span><strong>{bytes(totalPayload)}</strong><small>separate accounting</small></div><div><span>Tracked subjects</span><strong>{data.userTotals.length}</strong><small>selected node</small></div></div><Panel title="Interface traffic" meta="Received and sent counters"><TrafficChart points={data.interfaceTraffic} height={230}/></Panel><div className="traffic-grid"><Panel title="Per-user payload" meta="Top five series"><TrafficChart points={data.userTraffic} mode="user" height={170}/></Panel><Panel title="Top users" meta="Selected range">{topUsers.length ? <div className="ranking">{topUsers.slice(0, 6).map((user, index) => { const total = user.rxBytes + user.txBytes; return <div key={user.subject}><span>{user.subject}</span><code>{bytes(total)}</code><Progress value={index === 0 ? 100 : total / Math.max(1, topUsers[0].rxBytes + topUsers[0].txBytes) * 100}/></div> })}</div> : <Empty title="No user totals"/>}</Panel></div><Panel title="Quotas" action={<button className="button secondary" type="button" disabled={!nodeId} onClick={() => setQuota('new')}><Icon name="plus" size={15}/> Set quota</button>}>{data.quotas.length ? <div className="table-scroll"><table><thead><tr><th>User</th><th>Period</th><th>Usage</th><th>Limit</th><th>Policy</th><th>State</th><th/></tr></thead><tbody>{data.quotas.map(item => { const pct = item.usedBytes / item.quota.limitBytes * 100; return <tr key={item.quota.userTag}><td><strong>{item.quota.userTag}</strong></td><td>{item.quota.period.toLowerCase()}</td><td><div className="quota-cell"><span>{bytes(item.usedBytes)} · {pct.toFixed(0)}%</span><Progress value={pct} color={item.exceeded ? '#f2635f' : pct > 75 ? '#f0b429' : '#4fd1a5'}/></div></td><td className="mono">{bytes(item.quota.limitBytes)}</td><td><span className={`event-chip ${item.quota.action === 'DISABLE' ? 'security' : 'status'}`}>{item.quota.action.toLowerCase()}</span></td><td>{item.exceeded ? <span className="bad-text">exceeded</span> : item.quota.enabled ? 'active' : 'disabled'}</td><td className="row-actions"><button type="button" onClick={() => setQuota(item)}>Edit</button><ConfirmButton onConfirm={() => void action(() => api.deleteQuota(item.quota.nodeId, item.quota.userTag, item.quota.version))}>Remove</ConfirmButton></td></tr> })}</tbody></table></div> : <Empty title="No quotas"/>}</Panel>
    {quota && nodeId ? <QuotaModal item={quota === 'new' ? undefined : quota} users={data.catalog?.users.map(user => user.id) ?? []} busy={busy} onClose={() => setQuota(undefined)} onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const userTag = String(form.get('userTag')); const existing = quota === 'new' ? undefined : quota; void action(async () => { await api.putQuota(nodeId, userTag, { period: String(form.get('period')), limitBytes: Math.round(Number(form.get('limitGb')) * 1_000_000_000), action: String(form.get('action')), enabled: form.get('enabled') === 'on' }, existing?.quota.version); setQuota(undefined) }) }}/>: null}</>
}

function QuotaModal({ item, users, busy, onClose, onSubmit }: { item?: TrafficQuotaUsage; users: string[]; busy: boolean; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  return <Modal title={item ? `Edit quota · ${item.quota.userTag}` : 'Set traffic quota'} submitLabel="Save quota" busy={busy} onClose={onClose} onSubmit={onSubmit}><Field label="User"><select name="userTag" defaultValue={item?.quota.userTag} disabled={Boolean(item)}>{users.map(user => <option key={user}>{user}</option>)}</select>{item ? <input type="hidden" name="userTag" value={item.quota.userTag}/> : null}</Field><Field label="Period"><select name="period" defaultValue={item?.quota.period.toLowerCase() ?? 'monthly'}><option value="daily">Daily</option><option value="monthly">Monthly</option></select></Field><Field label="Limit, GB"><input required name="limitGb" type="number" min="0.001" step="0.001" defaultValue={item ? item.quota.limitBytes / 1_000_000_000 : 100}/></Field><Field label="Action"><select name="action" defaultValue={item?.quota.action.toLowerCase() ?? 'alert'}><option value="alert">Alert</option><option value="disable">Disable user</option></select></Field><label className="check-field"><input name="enabled" type="checkbox" defaultChecked={item?.quota.enabled ?? true}/> Enabled</label></Modal>
}
