// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: api/node/v1/node.proto

package nodev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeControlService_Enroll_FullMethodName  = "/bproxy.node.v1.NodeControlService/Enroll"
	NodeControlService_Renew_FullMethodName   = "/bproxy.node.v1.NodeControlService/Renew"
	NodeControlService_Connect_FullMethodName = "/bproxy.node.v1.NodeControlService/Connect"
)

// NodeControlServiceClient is the client API for NodeControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeControlServiceClient interface {
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	Renew(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeEvent, HubCommand], error)
}

type nodeControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeControlServiceClient(cc grpc.ClientConnInterface) NodeControlServiceClient {
	return &nodeControlServiceClient{cc}
}

func (c *nodeControlServiceClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, NodeControlService_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlServiceClient) Renew(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, NodeControlService_Renew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeEvent, HubCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeControlService_ServiceDesc.Streams[0], NodeControlService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NodeEvent, HubCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeControlService_ConnectClient = grpc.BidiStreamingClient[NodeEvent, HubCommand]

// NodeControlServiceServer is the server API for NodeControlService service.
// All implementations must embed UnimplementedNodeControlServiceServer
// for forward compatibility.
type NodeControlServiceServer interface {
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	Renew(context.Context, *RenewRequest) (*EnrollResponse, error)
	Connect(grpc.BidiStreamingServer[NodeEvent, HubCommand]) error
	mustEmbedUnimplementedNodeControlServiceServer()
}

// UnimplementedNodeControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeControlServiceServer struct{}

func (UnimplementedNodeControlServiceServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedNodeControlServiceServer) Renew(context.Context, *RenewRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Renew not implemented")
}
func (UnimplementedNodeControlServiceServer) Connect(grpc.BidiStreamingServer[NodeEvent, HubCommand]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedNodeControlServiceServer) mustEmbedUnimplementedNodeControlServiceServer() {}
func (UnimplementedNodeControlServiceServer) testEmbeddedByValue()                            {}

// UnsafeNodeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeControlServiceServer will
// result in compilation errors.
type UnsafeNodeControlServiceServer interface {
	mustEmbedUnimplementedNodeControlServiceServer()
}

func RegisterNodeControlServiceServer(s grpc.ServiceRegistrar, srv NodeControlServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeControlService_ServiceDesc, srv)
}

func _NodeControlService_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServiceServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControlService_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServiceServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControlService_Renew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServiceServer).Renew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControlService_Renew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServiceServer).Renew(ctx, req.(*RenewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControlService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeControlServiceServer).Connect(&grpc.GenericServerStream[NodeEvent, HubCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeControlService_ConnectServer = grpc.BidiStreamingServer[NodeEvent, HubCommand]

// NodeControlService_ServiceDesc is the grpc.ServiceDesc for NodeControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bproxy.node.v1.NodeControlService",
	HandlerType: (*NodeControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _NodeControlService_Enroll_Handler,
		},
		{
			MethodName: "Renew",
			Handler:    _NodeControlService_Renew_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _NodeControlService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/node/v1/node.proto",
}
