// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/node/v1/node.proto

package nodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	CsrPem        []byte                 `protobuf:"bytes,3,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_api_node_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_node_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_api_node_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

func (x *EnrollRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type EnrollResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CertificatePem   []byte                 `protobuf:"bytes,1,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	CaCertificatePem []byte                 `protobuf:"bytes,2,opt,name=ca_certificate_pem,json=caCertificatePem,proto3" json:"ca_certificate_pem,omitempty"`
	ExpiresAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_api_node_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_node_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_api_node_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetCertificatePem() []byte {
	if x != nil {
		return x.CertificatePem
	}
	return nil
}

func (x *EnrollResponse) GetCaCertificatePem() []byte {
	if x != nil {
		return x.CaCertificatePem
	}
	return nil
}

func (x *EnrollResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type RenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsrPem        []byte                 `protobuf:"bytes,1,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewRequest) Reset() {
	*x = RenewRequest{}
	mi := &file_api_node_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRequest) ProtoMessage() {}

func (x *RenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_node_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRequest.ProtoReflect.Descriptor instead.
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return file_api_node_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *RenewRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

func (x *RenewRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type NodeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*NodeEvent_Hello
	//	*NodeEvent_ApplyResult
	//	*NodeEvent_Heartbeat
	//	*NodeEvent_InterfaceTraffic
	//	*NodeEvent_UserTraffic
	Payload       isNodeEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEvent) Reset() {
	*x = NodeEvent{}
	mi := &file_api_node_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEvent) ProtoMessage() {}

func (x *NodeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_node_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEvent.ProtoReflect.Descriptor instead.
func (*NodeEvent) Descriptor() ([]byte, []int) {
	return file_api_node_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *NodeEvent) GetPayload() isNodeEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NodeEvent) GetHello() *NodeHello {
	if x != nil {
		if x, ok := x.Payload.(*NodeEvent_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *NodeEvent) GetApplyResult() *ApplyResult {
	if x != nil {
		if x, ok := x.Payload.(*NodeEvent_ApplyResult); ok {
			return x.ApplyResult
		}
	}
	return nil
}

func (x *NodeEvent) GetHeartbeat() *NodeHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*NodeEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *NodeEvent) GetInterfaceTraffic() *InterfaceTrafficBatch {
	if x != nil {
		if x, ok := x.Payload.(*NodeEvent_InterfaceTraffic); ok {
			return x.InterfaceTraffic
		}
	}
	return nil
}

func (x *NodeEvent) GetUserTraffic() *UserTrafficBatch {
	if x != nil {
		if x, ok := x.Payload.(*NodeEvent_UserTraffic); ok {
			return x.UserTraffic
		}
	}
	return nil
}

type isNodeEvent_Payload interface {
	isNodeEvent_Payload()
}

type NodeEvent_Hello struct {
	Hello *NodeHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type NodeEvent_ApplyResult struct {
	ApplyResult *ApplyResult `protobuf:"bytes,2,opt,name=apply_result,json=applyResult,proto3,oneof"`
}

type NodeEvent_Heartbeat struct {
	Heartbeat *NodeHeartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type NodeEvent_InterfaceTraffic struct {
	InterfaceTraffic *InterfaceTrafficBatch `protobuf:"bytes,4,opt,name=interface_traffic,json=interfaceTraffic,proto3,oneof"`
}

type NodeEvent_UserTraffic struct {
	UserTraffic *UserTrafficBatch `protobuf:"bytes,5,opt,name=user_traffic,json=userTraffic,proto3,oneof"`
}

func (*NodeEvent_Hello) isNodeEvent_Payload() {}

func (*NodeEvent_ApplyResult) isNodeEvent_Payload() {}

func (*NodeEvent_Heartbeat) isNodeEvent_Payload() {}

func (*NodeEvent_InterfaceTraffic) isNodeEvent_Payload() {}

func (*NodeEvent_UserTraffic) isNodeEvent_Payload() {}

type HubCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*HubCommand_DesiredState
	//	*HubCommand_TrafficAck
	Payload       isHubCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubCommand) Reset() {
	*x = HubCommand{}
	mi := &file_api_node_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubCommand) ProtoMessage() {}

func (x *HubCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_node_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubCommand.ProtoReflect.Descriptor instead.
func (*HubCommand) Descriptor() ([]byte, []int) {
	return file_api_node_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *HubCommand) GetPayload() isHubCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HubCommand) GetDesiredState() *DesiredState {
	if x != nil {
		if x, ok := x.Payload.(*HubCommand_DesiredState); ok {
			return x.DesiredState
		}
	}
	return nil
}

func (x *HubCommand) GetTrafficAck() *TrafficAck {
	if x != nil {
		if x, ok := x.Payload.(*HubCommand_TrafficAck); ok {
			return x.TrafficAck
		}
	}
	return nil
}

type isHubCommand_Payload interface {
	isHubCommand_Payload()
}

type HubCommand_DesiredState struct {
	DesiredState *DesiredState `protobuf:"bytes,1,opt,name=desired_state,json=desiredState,proto3,oneof"`
}

type HubCommand_TrafficAck struct {
	TrafficAck *TrafficAck `protobuf:"bytes,2,opt,name=traffic_ack,json=trafficAck,proto3,oneof"`
}

func (*HubCommand_DesiredState) isHubCommand_Payload() {}

func (*HubCommand_TrafficAck) isHubCommand_Payload() {}

type NodeHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	BootId          string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	AgentVersion    string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	CoreVersion     string                 `protobuf:"bytes,4,opt,name=core_version,json=coreVersion,proto3" json:"core_version,omitempty"`
	AppliedRevision uint64                 `protobuf:"varint,5,opt,name=applied_revision,json=appliedRevision,proto3" json:"applied_revision,omitempty"`
	ConfigSha256    string                 `protobuf:"bytes,6,opt,name=config_sha256,json=configSha256,proto3" json:"config_sha256,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeHello) Reset() {
	*x = NodeHello{}
	mi := &file_api_node_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHello) ProtoMessage() {}

func (x *NodeHello) ProtoReflect() protoreflect.Message {
	mi := &file_api_node_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHello.ProtoReflect.Descriptor instead.
func (*NodeHello) Descriptor() ([]byte, []int) {
	return file_api_node_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *NodeHello) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeHello) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *NodeHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *NodeHello) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

func (x *NodeHello) GetAppliedRevision() uint64 {
	if x != nil {
		return x.AppliedRevision
	}
	return 0
}

func (x *NodeHello) GetConfigSha256() string {
	if x != nil {
		return x.ConfigSha256
	}
	return ""
}

type DesiredState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	ConfigToml    []byte                 `protobuf:"bytes,2,opt,name=config_toml,json=configToml,proto3" json:"config_toml,omitempty"`
	ConfigSha256  string                 `protobuf:"bytes,3,opt,name=config_sha256,json=configSha256,proto3" json:"config_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesiredState) Reset() {
	*x = DesiredState{}
	mi := &file_api_node_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredState) ProtoMessage() {}

func (x *DesiredState) ProtoReflect() protoreflect.Message {
	mi := &file_api_node_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredState.ProtoReflect.Descriptor instead.
func (*DesiredState) Descriptor() ([]byte, []int) {
	return file_api_node_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *DesiredState) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DesiredState) GetConfigToml() []byte {
	if x != nil {
		return x.ConfigToml
	}
	return nil
}

func (x *DesiredState) GetConfigSha256() string {
	if x != nil {
		return x.ConfigSha256
	}
	return ""
}

type ApplyResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DesiredRevision uint64                 `protobuf:"varint,1,opt,name=desired_revision,json=desiredRevision,proto3" json:"desired_revision,omitempty"`
	RuntimeRevision uint64                 `protobuf:"varint,2,opt,name=runtime_revision,json=runtimeRevision,proto3" json:"runtime_revision,omitempty"`
	ConfigSha256    string                 `protobuf:"bytes,3,opt,name=config_sha256,json=configSha256,proto3" json:"config_sha256,omitempty"`
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	AppliedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplyResult) Reset() {
	*x = ApplyResult{}
	mi := &file_api_node_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResult) ProtoMessage() {}

func (x *ApplyResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_node_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResult.ProtoReflect.Descriptor instead.
func (*ApplyResult) Descriptor() ([]byte, []int) {
	return file_api_node_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *ApplyResult) GetDesiredRevision() uint64 {
	if x != nil {
		return x.DesiredRevision
	}
	return 0
}

func (x *ApplyResult) GetRuntimeRevision() uint64 {
	if x != nil {
		return x.RuntimeRevision
	}
	return 0
}

func (x *ApplyResult) GetConfigSha256() string {
	if x != nil {
		return x.ConfigSha256
	}
	return ""
}

func (x *ApplyResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ApplyResult) GetAppliedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AppliedAt
	}
	return nil
}

type NodeHeartbeat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SampledAt       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=sampled_at,json=sampledAt,proto3" json:"sampled_at,omitempty"`
	CoreRunning     bool                   `protobuf:"varint,2,opt,name=core_running,json=coreRunning,proto3" json:"core_running,omitempty"`
	CoreReady       bool                   `protobuf:"varint,3,opt,name=core_ready,json=coreReady,proto3" json:"core_ready,omitempty"`
	AppliedRevision uint64                 `protobuf:"varint,4,opt,name=applied_revision,json=appliedRevision,proto3" json:"applied_revision,omitempty"`
	Error           string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeHeartbeat) Reset() {
	*x = NodeHeartbeat{}
	mi := &file_api_node_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHeartbeat) ProtoMessage() {}

func (x *NodeHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_node_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHeartbeat.ProtoReflect.Descriptor instead.
func (*NodeHeartbeat) Descriptor() ([]byte, []int) {
	return file_api_node_v1_node_proto_rawDescGZIP(), []int{8}
}

func (x *NodeHeartbeat) GetSampledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SampledAt
	}
	return nil
}

func (x *NodeHeartbeat) GetCoreRunning() bool {
	if x != nil {
		return x.CoreRunning
	}
	return false
}

func (x *NodeHeartbeat) GetCoreReady() bool {
	if x != nil {
		return x.CoreReady
	}
	return false
}

func (x *NodeHeartbeat) GetAppliedRevision() uint64 {
	if x != nil {
		return x.AppliedRevision
	}
	return 0
}

func (x *NodeHeartbeat) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Raw traffic of the node container network namespace. This includes
// BoardProxy payload, board transport and control-plane overhead.
type InterfaceTrafficBatch struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	BatchId       string                   `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	IntervalStart *timestamppb.Timestamp   `protobuf:"bytes,2,opt,name=interval_start,json=intervalStart,proto3" json:"interval_start,omitempty"`
	IntervalEnd   *timestamppb.Timestamp   `protobuf:"bytes,3,opt,name=interval_end,json=intervalEnd,proto3" json:"interval_end,omitempty"`
	Interfaces    []*InterfaceTrafficDelta `protobuf:"bytes,4,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceTrafficBatch) Reset() {
	*x = InterfaceTrafficBatch{}
	mi := &file_api_node_v1_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceTrafficBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceTrafficBatch) ProtoMessage() {}

func (x *InterfaceTrafficBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_node_v1_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceTrafficBatch.ProtoReflect.Descriptor instead.
func (*InterfaceTrafficBatch) Descriptor() ([]byte, []int) {
	return file_api_node_v1_node_proto_rawDescGZIP(), []int{9}
}

func (x *InterfaceTrafficBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *InterfaceTrafficBatch) GetIntervalStart() *timestamppb.Timestamp {
	if x != nil {
		return x.IntervalStart
	}
	return nil
}

func (x *InterfaceTrafficBatch) GetIntervalEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.IntervalEnd
	}
	return nil
}

func (x *InterfaceTrafficBatch) GetInterfaces() []*InterfaceTrafficDelta {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type InterfaceTrafficDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	RxBytes       uint64                 `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       uint64                 `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxPackets     uint64                 `protobuf:"varint,4,opt,name=rx_packets,json=rxPackets,proto3" json:"rx_packets,omitempty"`
	TxPackets     uint64                 `protobuf:"varint,5,opt,name=tx_packets,json=txPackets,proto3" json:"tx_packets,omitempty"`
	RxErrors      uint64                 `protobuf:"varint,6,opt,name=rx_errors,json=rxErrors,proto3" json:"rx_errors,omitempty"`
	TxErrors      uint64                 `protobuf:"varint,7,opt,name=tx_errors,json=txErrors,proto3" json:"tx_errors,omitempty"`
	RxDropped     uint64                 `protobuf:"varint,8,opt,name=rx_dropped,json=rxDropped,proto3" json:"rx_dropped,omitempty"`
	TxDropped     uint64                 `protobuf:"varint,9,opt,name=tx_dropped,json=txDropped,proto3" json:"tx_dropped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceTrafficDelta) Reset() {
	*x = InterfaceTrafficDelta{}
	mi := &file_api_node_v1_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceTrafficDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceTrafficDelta) ProtoMessage() {}

func (x *InterfaceTrafficDelta) ProtoReflect() protoreflect.Message {
	mi := &file_api_node_v1_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceTrafficDelta.ProtoReflect.Descriptor instead.
func (*InterfaceTrafficDelta) Descriptor() ([]byte, []int) {
	return file_api_node_v1_node_proto_rawDescGZIP(), []int{10}
}

func (x *InterfaceTrafficDelta) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *InterfaceTrafficDelta) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *InterfaceTrafficDelta) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *InterfaceTrafficDelta) GetRxPackets() uint64 {
	if x != nil {
		return x.RxPackets
	}
	return 0
}

func (x *InterfaceTrafficDelta) GetTxPackets() uint64 {
	if x != nil {
		return x.TxPackets
	}
	return 0
}

func (x *InterfaceTrafficDelta) GetRxErrors() uint64 {
	if x != nil {
		return x.RxErrors
	}
	return 0
}

func (x *InterfaceTrafficDelta) GetTxErrors() uint64 {
	if x != nil {
		return x.TxErrors
	}
	return 0
}

func (x *InterfaceTrafficDelta) GetRxDropped() uint64 {
	if x != nil {
		return x.RxDropped
	}
	return 0
}

func (x *InterfaceTrafficDelta) GetTxDropped() uint64 {
	if x != nil {
		return x.TxDropped
	}
	return 0
}

// Decrypted BoardProxy payload attributed by core. It is never summed with
// InterfaceTrafficBatch.
type UserTrafficBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	IntervalStart *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=interval_start,json=intervalStart,proto3" json:"interval_start,omitempty"`
	IntervalEnd   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=interval_end,json=intervalEnd,proto3" json:"interval_end,omitempty"`
	Users         []*UserTrafficDelta    `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTrafficBatch) Reset() {
	*x = UserTrafficBatch{}
	mi := &file_api_node_v1_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTrafficBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTrafficBatch) ProtoMessage() {}

func (x *UserTrafficBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_node_v1_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTrafficBatch.ProtoReflect.Descriptor instead.
func (*UserTrafficBatch) Descriptor() ([]byte, []int) {
	return file_api_node_v1_node_proto_rawDescGZIP(), []int{11}
}

func (x *UserTrafficBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *UserTrafficBatch) GetIntervalStart() *timestamppb.Timestamp {
	if x != nil {
		return x.IntervalStart
	}
	return nil
}

func (x *UserTrafficBatch) GetIntervalEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.IntervalEnd
	}
	return nil
}

func (x *UserTrafficBatch) GetUsers() []*UserTrafficDelta {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserTrafficDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserTag       string                 `protobuf:"bytes,1,opt,name=user_tag,json=userTag,proto3" json:"user_tag,omitempty"`
	RxBytes       uint64                 `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"` // client upload
	TxBytes       uint64                 `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"` // client download
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTrafficDelta) Reset() {
	*x = UserTrafficDelta{}
	mi := &file_api_node_v1_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTrafficDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTrafficDelta) ProtoMessage() {}

func (x *UserTrafficDelta) ProtoReflect() protoreflect.Message {
	mi := &file_api_node_v1_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTrafficDelta.ProtoReflect.Descriptor instead.
func (*UserTrafficDelta) Descriptor() ([]byte, []int) {
	return file_api_node_v1_node_proto_rawDescGZIP(), []int{12}
}

func (x *UserTrafficDelta) GetUserTag() string {
	if x != nil {
		return x.UserTag
	}
	return ""
}

func (x *UserTrafficDelta) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *UserTrafficDelta) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

type TrafficAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficAck) Reset() {
	*x = TrafficAck{}
	mi := &file_api_node_v1_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficAck) ProtoMessage() {}

func (x *TrafficAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_node_v1_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficAck.ProtoReflect.Descriptor instead.
func (*TrafficAck) Descriptor() ([]byte, []int) {
	return file_api_node_v1_node_proto_rawDescGZIP(), []int{13}
}

func (x *TrafficAck) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

var File_api_node_v1_node_proto protoreflect.FileDescriptor

const file_api_node_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x16api/node/v1/node.proto\x12\x0ebproxy.node.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"|\n" +
	"\rEnrollRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x17\n" +
	"\acsr_pem\x18\x03 \x01(\fR\x06csrPem\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\"\xa2\x01\n" +
	"\x0eEnrollResponse\x12'\n" +
	"\x0fcertificate_pem\x18\x01 \x01(\fR\x0ecertificatePem\x12,\n" +
	"\x12ca_certificate_pem\x18\x02 \x01(\fR\x10caCertificatePem\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"L\n" +
	"\fRenewRequest\x12\x17\n" +
	"\acsr_pem\x18\x01 \x01(\fR\x06csrPem\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\"\xe7\x02\n" +
	"\tNodeEvent\x121\n" +
	"\x05hello\x18\x01 \x01(\v2\x19.bproxy.node.v1.NodeHelloH\x00R\x05hello\x12@\n" +
	"\fapply_result\x18\x02 \x01(\v2\x1b.bproxy.node.v1.ApplyResultH\x00R\vapplyResult\x12=\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1d.bproxy.node.v1.NodeHeartbeatH\x00R\theartbeat\x12T\n" +
	"\x11interface_traffic\x18\x04 \x01(\v2%.bproxy.node.v1.InterfaceTrafficBatchH\x00R\x10interfaceTraffic\x12E\n" +
	"\fuser_traffic\x18\x05 \x01(\v2 .bproxy.node.v1.UserTrafficBatchH\x00R\vuserTrafficB\t\n" +
	"\apayload\"\x9b\x01\n" +
	"\n" +
	"HubCommand\x12C\n" +
	"\rdesired_state\x18\x01 \x01(\v2\x1c.bproxy.node.v1.DesiredStateH\x00R\fdesiredState\x12=\n" +
	"\vtraffic_ack\x18\x02 \x01(\v2\x1a.bproxy.node.v1.TrafficAckH\x00R\n" +
	"trafficAckB\t\n" +
	"\apayload\"\xd5\x01\n" +
	"\tNodeHello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12!\n" +
	"\fcore_version\x18\x04 \x01(\tR\vcoreVersion\x12)\n" +
	"\x10applied_revision\x18\x05 \x01(\x04R\x0fappliedRevision\x12#\n" +
	"\rconfig_sha256\x18\x06 \x01(\tR\fconfigSha256\"p\n" +
	"\fDesiredState\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x12\x1f\n" +
	"\vconfig_toml\x18\x02 \x01(\fR\n" +
	"configToml\x12#\n" +
	"\rconfig_sha256\x18\x03 \x01(\tR\fconfigSha256\"\xd9\x01\n" +
	"\vApplyResult\x12)\n" +
	"\x10desired_revision\x18\x01 \x01(\x04R\x0fdesiredRevision\x12)\n" +
	"\x10runtime_revision\x18\x02 \x01(\x04R\x0fruntimeRevision\x12#\n" +
	"\rconfig_sha256\x18\x03 \x01(\tR\fconfigSha256\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x129\n" +
	"\n" +
	"applied_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tappliedAt\"\xcd\x01\n" +
	"\rNodeHeartbeat\x129\n" +
	"\n" +
	"sampled_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tsampledAt\x12!\n" +
	"\fcore_running\x18\x02 \x01(\bR\vcoreRunning\x12\x1d\n" +
	"\n" +
	"core_ready\x18\x03 \x01(\bR\tcoreReady\x12)\n" +
	"\x10applied_revision\x18\x04 \x01(\x04R\x0fappliedRevision\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xfb\x01\n" +
	"\x15InterfaceTrafficBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12A\n" +
	"\x0einterval_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rintervalStart\x12=\n" +
	"\finterval_end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vintervalEnd\x12E\n" +
	"\n" +
	"interfaces\x18\x04 \x03(\v2%.bproxy.node.v1.InterfaceTrafficDeltaR\n" +
	"interfaces\"\xa1\x02\n" +
	"\x15InterfaceTrafficDelta\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x19\n" +
	"\brx_bytes\x18\x02 \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x03 \x01(\x04R\atxBytes\x12\x1d\n" +
	"\n" +
	"rx_packets\x18\x04 \x01(\x04R\trxPackets\x12\x1d\n" +
	"\n" +
	"tx_packets\x18\x05 \x01(\x04R\ttxPackets\x12\x1b\n" +
	"\trx_errors\x18\x06 \x01(\x04R\brxErrors\x12\x1b\n" +
	"\ttx_errors\x18\a \x01(\x04R\btxErrors\x12\x1d\n" +
	"\n" +
	"rx_dropped\x18\b \x01(\x04R\trxDropped\x12\x1d\n" +
	"\n" +
	"tx_dropped\x18\t \x01(\x04R\ttxDropped\"\xe7\x01\n" +
	"\x10UserTrafficBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12A\n" +
	"\x0einterval_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rintervalStart\x12=\n" +
	"\finterval_end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vintervalEnd\x126\n" +
	"\x05users\x18\x04 \x03(\v2 .bproxy.node.v1.UserTrafficDeltaR\x05users\"c\n" +
	"\x10UserTrafficDelta\x12\x19\n" +
	"\buser_tag\x18\x01 \x01(\tR\auserTag\x12\x19\n" +
	"\brx_bytes\x18\x02 \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x03 \x01(\x04R\atxBytes\"'\n" +
	"\n" +
	"TrafficAck\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId2\xea\x01\n" +
	"\x12NodeControlService\x12G\n" +
	"\x06Enroll\x12\x1d.bproxy.node.v1.EnrollRequest\x1a\x1e.bproxy.node.v1.EnrollResponse\x12E\n" +
	"\x05Renew\x12\x1c.bproxy.node.v1.RenewRequest\x1a\x1e.bproxy.node.v1.EnrollResponse\x12D\n" +
	"\aConnect\x12\x19.bproxy.node.v1.NodeEvent\x1a\x1a.bproxy.node.v1.HubCommand(\x010\x01B)Z'bproxy-control-plane/api/node/v1;nodev1b\x06proto3"

var (
	file_api_node_v1_node_proto_rawDescOnce sync.Once
	file_api_node_v1_node_proto_rawDescData []byte
)

func file_api_node_v1_node_proto_rawDescGZIP() []byte {
	file_api_node_v1_node_proto_rawDescOnce.Do(func() {
		file_api_node_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_node_v1_node_proto_rawDesc), len(file_api_node_v1_node_proto_rawDesc)))
	})
	return file_api_node_v1_node_proto_rawDescData
}

var file_api_node_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_node_v1_node_proto_goTypes = []any{
	(*EnrollRequest)(nil),         // 0: bproxy.node.v1.EnrollRequest
	(*EnrollResponse)(nil),        // 1: bproxy.node.v1.EnrollResponse
	(*RenewRequest)(nil),          // 2: bproxy.node.v1.RenewRequest
	(*NodeEvent)(nil),             // 3: bproxy.node.v1.NodeEvent
	(*HubCommand)(nil),            // 4: bproxy.node.v1.HubCommand
	(*NodeHello)(nil),             // 5: bproxy.node.v1.NodeHello
	(*DesiredState)(nil),          // 6: bproxy.node.v1.DesiredState
	(*ApplyResult)(nil),           // 7: bproxy.node.v1.ApplyResult
	(*NodeHeartbeat)(nil),         // 8: bproxy.node.v1.NodeHeartbeat
	(*InterfaceTrafficBatch)(nil), // 9: bproxy.node.v1.InterfaceTrafficBatch
	(*InterfaceTrafficDelta)(nil), // 10: bproxy.node.v1.InterfaceTrafficDelta
	(*UserTrafficBatch)(nil),      // 11: bproxy.node.v1.UserTrafficBatch
	(*UserTrafficDelta)(nil),      // 12: bproxy.node.v1.UserTrafficDelta
	(*TrafficAck)(nil),            // 13: bproxy.node.v1.TrafficAck
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_api_node_v1_node_proto_depIdxs = []int32{
	14, // 0: bproxy.node.v1.EnrollResponse.expires_at:type_name -> google.protobuf.Timestamp
	5,  // 1: bproxy.node.v1.NodeEvent.hello:type_name -> bproxy.node.v1.NodeHello
	7,  // 2: bproxy.node.v1.NodeEvent.apply_result:type_name -> bproxy.node.v1.ApplyResult
	8,  // 3: bproxy.node.v1.NodeEvent.heartbeat:type_name -> bproxy.node.v1.NodeHeartbeat
	9,  // 4: bproxy.node.v1.NodeEvent.interface_traffic:type_name -> bproxy.node.v1.InterfaceTrafficBatch
	11, // 5: bproxy.node.v1.NodeEvent.user_traffic:type_name -> bproxy.node.v1.UserTrafficBatch
	6,  // 6: bproxy.node.v1.HubCommand.desired_state:type_name -> bproxy.node.v1.DesiredState
	13, // 7: bproxy.node.v1.HubCommand.traffic_ack:type_name -> bproxy.node.v1.TrafficAck
	14, // 8: bproxy.node.v1.ApplyResult.applied_at:type_name -> google.protobuf.Timestamp
	14, // 9: bproxy.node.v1.NodeHeartbeat.sampled_at:type_name -> google.protobuf.Timestamp
	14, // 10: bproxy.node.v1.InterfaceTrafficBatch.interval_start:type_name -> google.protobuf.Timestamp
	14, // 11: bproxy.node.v1.InterfaceTrafficBatch.interval_end:type_name -> google.protobuf.Timestamp
	10, // 12: bproxy.node.v1.InterfaceTrafficBatch.interfaces:type_name -> bproxy.node.v1.InterfaceTrafficDelta
	14, // 13: bproxy.node.v1.UserTrafficBatch.interval_start:type_name -> google.protobuf.Timestamp
	14, // 14: bproxy.node.v1.UserTrafficBatch.interval_end:type_name -> google.protobuf.Timestamp
	12, // 15: bproxy.node.v1.UserTrafficBatch.users:type_name -> bproxy.node.v1.UserTrafficDelta
	0,  // 16: bproxy.node.v1.NodeControlService.Enroll:input_type -> bproxy.node.v1.EnrollRequest
	2,  // 17: bproxy.node.v1.NodeControlService.Renew:input_type -> bproxy.node.v1.RenewRequest
	3,  // 18: bproxy.node.v1.NodeControlService.Connect:input_type -> bproxy.node.v1.NodeEvent
	1,  // 19: bproxy.node.v1.NodeControlService.Enroll:output_type -> bproxy.node.v1.EnrollResponse
	1,  // 20: bproxy.node.v1.NodeControlService.Renew:output_type -> bproxy.node.v1.EnrollResponse
	4,  // 21: bproxy.node.v1.NodeControlService.Connect:output_type -> bproxy.node.v1.HubCommand
	19, // [19:22] is the sub-list for method output_type
	16, // [16:19] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_node_v1_node_proto_init() }
func file_api_node_v1_node_proto_init() {
	if File_api_node_v1_node_proto != nil {
		return
	}
	file_api_node_v1_node_proto_msgTypes[3].OneofWrappers = []any{
		(*NodeEvent_Hello)(nil),
		(*NodeEvent_ApplyResult)(nil),
		(*NodeEvent_Heartbeat)(nil),
		(*NodeEvent_InterfaceTraffic)(nil),
		(*NodeEvent_UserTraffic)(nil),
	}
	file_api_node_v1_node_proto_msgTypes[4].OneofWrappers = []any{
		(*HubCommand_DesiredState)(nil),
		(*HubCommand_TrafficAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_node_v1_node_proto_rawDesc), len(file_api_node_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_node_v1_node_proto_goTypes,
		DependencyIndexes: file_api_node_v1_node_proto_depIdxs,
		MessageInfos:      file_api_node_v1_node_proto_msgTypes,
	}.Build()
	File_api_node_v1_node_proto = out.File
	file_api_node_v1_node_proto_goTypes = nil
	file_api_node_v1_node_proto_depIdxs = nil
}
