// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/control/v1/control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Revision        uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	ConfigSource    string                 `protobuf:"bytes,2,opt,name=config_source,json=configSource,proto3" json:"config_source,omitempty"`
	ServerPublicKey string                 `protobuf:"bytes,3,opt,name=server_public_key,json=serverPublicKey,proto3" json:"server_public_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuntimeInfo) Reset() {
	*x = RuntimeInfo{}
	mi := &file_api_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfo) ProtoMessage() {}

func (x *RuntimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfo.ProtoReflect.Descriptor instead.
func (*RuntimeInfo) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *RuntimeInfo) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *RuntimeInfo) GetConfigSource() string {
	if x != nil {
		return x.ConfigSource
	}
	return ""
}

func (x *RuntimeInfo) GetServerPublicKey() string {
	if x != nil {
		return x.ServerPublicKey
	}
	return ""
}

type RevisionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExpectedRevision uint64                 `protobuf:"varint,1,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RevisionRequest) Reset() {
	*x = RevisionRequest{}
	mi := &file_api_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevisionRequest) ProtoMessage() {}

func (x *RevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevisionRequest.ProtoReflect.Descriptor instead.
func (*RevisionRequest) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *RevisionRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type ResourceRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExpectedRevision uint64                 `protobuf:"varint,1,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	Tag              string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	mi := &file_api_control_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *ResourceRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type MutationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationResult) Reset() {
	*x = MutationResult{}
	mi := &file_api_control_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationResult) ProtoMessage() {}

func (x *MutationResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationResult.ProtoReflect.Descriptor instead.
func (*MutationResult) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *MutationResult) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type SetEnabledRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExpectedRevision uint64                 `protobuf:"varint,1,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	Tag              string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Enabled          bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetEnabledRequest) Reset() {
	*x = SetEnabledRequest{}
	mi := &file_api_control_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEnabledRequest) ProtoMessage() {}

func (x *SetEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEnabledRequest.ProtoReflect.Descriptor instead.
func (*SetEnabledRequest) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *SetEnabledRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *SetEnabledRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *SetEnabledRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type UserSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Enabled       *bool                  `protobuf:"varint,5,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	Boards        []string               `protobuf:"bytes,6,rep,name=boards,proto3" json:"boards,omitempty"`
	MaxSessions   int32                  `protobuf:"varint,7,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	MaxLanes      int32                  `protobuf:"varint,8,opt,name=max_lanes,json=maxLanes,proto3" json:"max_lanes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSpec) Reset() {
	*x = UserSpec{}
	mi := &file_api_control_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSpec) ProtoMessage() {}

func (x *UserSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSpec.ProtoReflect.Descriptor instead.
func (*UserSpec) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *UserSpec) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *UserSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSpec) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *UserSpec) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *UserSpec) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *UserSpec) GetBoards() []string {
	if x != nil {
		return x.Boards
	}
	return nil
}

func (x *UserSpec) GetMaxSessions() int32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

func (x *UserSpec) GetMaxLanes() int32 {
	if x != nil {
		return x.MaxLanes
	}
	return 0
}

type ReplaceUserRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExpectedRevision uint64                 `protobuf:"varint,1,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	User             *UserSpec              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReplaceUserRequest) Reset() {
	*x = ReplaceUserRequest{}
	mi := &file_api_control_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceUserRequest) ProtoMessage() {}

func (x *ReplaceUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceUserRequest.ProtoReflect.Descriptor instead.
func (*ReplaceUserRequest) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *ReplaceUserRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *ReplaceUserRequest) GetUser() *UserSpec {
	if x != nil {
		return x.User
	}
	return nil
}

type ApplySnapshotRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExpectedRevision uint64                 `protobuf:"varint,1,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	Users            []*UserSpec            `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Boards           []*BoardSpec           `protobuf:"bytes,3,rep,name=boards,proto3" json:"boards,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApplySnapshotRequest) Reset() {
	*x = ApplySnapshotRequest{}
	mi := &file_api_control_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplySnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplySnapshotRequest) ProtoMessage() {}

func (x *ApplySnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplySnapshotRequest.ProtoReflect.Descriptor instead.
func (*ApplySnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *ApplySnapshotRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *ApplySnapshotRequest) GetUsers() []*UserSpec {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ApplySnapshotRequest) GetBoards() []*BoardSpec {
	if x != nil {
		return x.Boards
	}
	return nil
}

type UserInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Tag                string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PublicKey          string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Enabled            bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Boards             []string               `protobuf:"bytes,5,rep,name=boards,proto3" json:"boards,omitempty"`
	MaxSessions        int32                  `protobuf:"varint,6,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	MaxLanes           int32                  `protobuf:"varint,7,opt,name=max_lanes,json=maxLanes,proto3" json:"max_lanes,omitempty"`
	ActiveSessions     int32                  `protobuf:"varint,8,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	RxBytesSinceStart  uint64                 `protobuf:"varint,9,opt,name=rx_bytes_since_start,json=rxBytesSinceStart,proto3" json:"rx_bytes_since_start,omitempty"`
	TxBytesSinceStart  uint64                 `protobuf:"varint,10,opt,name=tx_bytes_since_start,json=txBytesSinceStart,proto3" json:"tx_bytes_since_start,omitempty"`
	LastSeenSinceStart *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_seen_since_start,json=lastSeenSinceStart,proto3" json:"last_seen_since_start,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_api_control_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *UserInfo) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *UserInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UserInfo) GetBoards() []string {
	if x != nil {
		return x.Boards
	}
	return nil
}

func (x *UserInfo) GetMaxSessions() int32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

func (x *UserInfo) GetMaxLanes() int32 {
	if x != nil {
		return x.MaxLanes
	}
	return 0
}

func (x *UserInfo) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *UserInfo) GetRxBytesSinceStart() uint64 {
	if x != nil {
		return x.RxBytesSinceStart
	}
	return 0
}

func (x *UserInfo) GetTxBytesSinceStart() uint64 {
	if x != nil {
		return x.TxBytesSinceStart
	}
	return 0
}

func (x *UserInfo) GetLastSeenSinceStart() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenSinceStart
	}
	return nil
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Users         []*UserInfo            `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_api_control_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *ListUsersResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ListUsersResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type KeylinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keylink       string                 `protobuf:"bytes,1,opt,name=keylink,proto3" json:"keylink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeylinkResponse) Reset() {
	*x = KeylinkResponse{}
	mi := &file_api_control_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeylinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeylinkResponse) ProtoMessage() {}

func (x *KeylinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeylinkResponse.ProtoReflect.Descriptor instead.
func (*KeylinkResponse) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *KeylinkResponse) GetKeylink() string {
	if x != nil {
		return x.Keylink
	}
	return ""
}

type BoardSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	HubSlide      string                 `protobuf:"bytes,4,opt,name=hub_slide,json=hubSlide,proto3" json:"hub_slide,omitempty"`
	ApiBase       string                 `protobuf:"bytes,5,opt,name=api_base,json=apiBase,proto3" json:"api_base,omitempty"`
	GuestName     string                 `protobuf:"bytes,6,opt,name=guest_name,json=guestName,proto3" json:"guest_name,omitempty"`
	Enabled       *bool                  `protobuf:"varint,7,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	MaxLanes      int32                  `protobuf:"varint,8,opt,name=max_lanes,json=maxLanes,proto3" json:"max_lanes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardSpec) Reset() {
	*x = BoardSpec{}
	mi := &file_api_control_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardSpec) ProtoMessage() {}

func (x *BoardSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardSpec.ProtoReflect.Descriptor instead.
func (*BoardSpec) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *BoardSpec) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *BoardSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BoardSpec) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *BoardSpec) GetHubSlide() string {
	if x != nil {
		return x.HubSlide
	}
	return ""
}

func (x *BoardSpec) GetApiBase() string {
	if x != nil {
		return x.ApiBase
	}
	return ""
}

func (x *BoardSpec) GetGuestName() string {
	if x != nil {
		return x.GuestName
	}
	return ""
}

func (x *BoardSpec) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *BoardSpec) GetMaxLanes() int32 {
	if x != nil {
		return x.MaxLanes
	}
	return 0
}

type ReplaceBoardRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExpectedRevision uint64                 `protobuf:"varint,1,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	Board            *BoardSpec             `protobuf:"bytes,2,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReplaceBoardRequest) Reset() {
	*x = ReplaceBoardRequest{}
	mi := &file_api_control_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceBoardRequest) ProtoMessage() {}

func (x *ReplaceBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceBoardRequest.ProtoReflect.Descriptor instead.
func (*ReplaceBoardRequest) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{12}
}

func (x *ReplaceBoardRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *ReplaceBoardRequest) GetBoard() *BoardSpec {
	if x != nil {
		return x.Board
	}
	return nil
}

type BoardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *BoardSpec             `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardInfo) Reset() {
	*x = BoardInfo{}
	mi := &file_api_control_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardInfo) ProtoMessage() {}

func (x *BoardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardInfo.ProtoReflect.Descriptor instead.
func (*BoardInfo) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{13}
}

func (x *BoardInfo) GetConfig() *BoardSpec {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *BoardInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *BoardInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListBoardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Boards        []*BoardInfo           `protobuf:"bytes,2,rep,name=boards,proto3" json:"boards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBoardsResponse) Reset() {
	*x = ListBoardsResponse{}
	mi := &file_api_control_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBoardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBoardsResponse) ProtoMessage() {}

func (x *ListBoardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBoardsResponse.ProtoReflect.Descriptor instead.
func (*ListBoardsResponse) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{14}
}

func (x *ListBoardsResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ListBoardsResponse) GetBoards() []*BoardInfo {
	if x != nil {
		return x.Boards
	}
	return nil
}

type RuntimeStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StartedAt         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Revision          uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	UsersConfigured   int32                  `protobuf:"varint,3,opt,name=users_configured,json=usersConfigured,proto3" json:"users_configured,omitempty"`
	UsersEnabled      int32                  `protobuf:"varint,4,opt,name=users_enabled,json=usersEnabled,proto3" json:"users_enabled,omitempty"`
	UsersOnline       int32                  `protobuf:"varint,5,opt,name=users_online,json=usersOnline,proto3" json:"users_online,omitempty"`
	BoardsConfigured  int32                  `protobuf:"varint,6,opt,name=boards_configured,json=boardsConfigured,proto3" json:"boards_configured,omitempty"`
	BoardsEnabled     int32                  `protobuf:"varint,7,opt,name=boards_enabled,json=boardsEnabled,proto3" json:"boards_enabled,omitempty"`
	BoardsRunning     int32                  `protobuf:"varint,8,opt,name=boards_running,json=boardsRunning,proto3" json:"boards_running,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,9,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	ActiveLanes       int32                  `protobuf:"varint,10,opt,name=active_lanes,json=activeLanes,proto3" json:"active_lanes,omitempty"`
	ActiveStreams     int32                  `protobuf:"varint,11,opt,name=active_streams,json=activeStreams,proto3" json:"active_streams,omitempty"`
	RxBytesSinceStart uint64                 `protobuf:"varint,12,opt,name=rx_bytes_since_start,json=rxBytesSinceStart,proto3" json:"rx_bytes_since_start,omitempty"`
	TxBytesSinceStart uint64                 `protobuf:"varint,13,opt,name=tx_bytes_since_start,json=txBytesSinceStart,proto3" json:"tx_bytes_since_start,omitempty"`
	Users             []*UserRuntimeStats    `protobuf:"bytes,14,rep,name=users,proto3" json:"users,omitempty"`
	Boards            []*BoardRuntimeStats   `protobuf:"bytes,15,rep,name=boards,proto3" json:"boards,omitempty"`
	Network           *NetworkStats          `protobuf:"bytes,16,opt,name=network,proto3" json:"network,omitempty"`
	Transport         *TransportStats        `protobuf:"bytes,17,opt,name=transport,proto3" json:"transport,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RuntimeStats) Reset() {
	*x = RuntimeStats{}
	mi := &file_api_control_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeStats) ProtoMessage() {}

func (x *RuntimeStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeStats.ProtoReflect.Descriptor instead.
func (*RuntimeStats) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{15}
}

func (x *RuntimeStats) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *RuntimeStats) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *RuntimeStats) GetUsersConfigured() int32 {
	if x != nil {
		return x.UsersConfigured
	}
	return 0
}

func (x *RuntimeStats) GetUsersEnabled() int32 {
	if x != nil {
		return x.UsersEnabled
	}
	return 0
}

func (x *RuntimeStats) GetUsersOnline() int32 {
	if x != nil {
		return x.UsersOnline
	}
	return 0
}

func (x *RuntimeStats) GetBoardsConfigured() int32 {
	if x != nil {
		return x.BoardsConfigured
	}
	return 0
}

func (x *RuntimeStats) GetBoardsEnabled() int32 {
	if x != nil {
		return x.BoardsEnabled
	}
	return 0
}

func (x *RuntimeStats) GetBoardsRunning() int32 {
	if x != nil {
		return x.BoardsRunning
	}
	return 0
}

func (x *RuntimeStats) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *RuntimeStats) GetActiveLanes() int32 {
	if x != nil {
		return x.ActiveLanes
	}
	return 0
}

func (x *RuntimeStats) GetActiveStreams() int32 {
	if x != nil {
		return x.ActiveStreams
	}
	return 0
}

func (x *RuntimeStats) GetRxBytesSinceStart() uint64 {
	if x != nil {
		return x.RxBytesSinceStart
	}
	return 0
}

func (x *RuntimeStats) GetTxBytesSinceStart() uint64 {
	if x != nil {
		return x.TxBytesSinceStart
	}
	return 0
}

func (x *RuntimeStats) GetUsers() []*UserRuntimeStats {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *RuntimeStats) GetBoards() []*BoardRuntimeStats {
	if x != nil {
		return x.Boards
	}
	return nil
}

func (x *RuntimeStats) GetNetwork() *NetworkStats {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *RuntimeStats) GetTransport() *TransportStats {
	if x != nil {
		return x.Transport
	}
	return nil
}

type UserRuntimeStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Tag                string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enabled            bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Online             bool                   `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
	LastSeenSinceStart *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_seen_since_start,json=lastSeenSinceStart,proto3" json:"last_seen_since_start,omitempty"`
	Connections        int32                  `protobuf:"varint,6,opt,name=connections,proto3" json:"connections,omitempty"`
	Lanes              int32                  `protobuf:"varint,7,opt,name=lanes,proto3" json:"lanes,omitempty"`
	Streams            int32                  `protobuf:"varint,8,opt,name=streams,proto3" json:"streams,omitempty"`
	RxBytesSinceStart  uint64                 `protobuf:"varint,9,opt,name=rx_bytes_since_start,json=rxBytesSinceStart,proto3" json:"rx_bytes_since_start,omitempty"`
	TxBytesSinceStart  uint64                 `protobuf:"varint,10,opt,name=tx_bytes_since_start,json=txBytesSinceStart,proto3" json:"tx_bytes_since_start,omitempty"`
	MaxSessions        int32                  `protobuf:"varint,11,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	MaxLanes           int32                  `protobuf:"varint,12,opt,name=max_lanes,json=maxLanes,proto3" json:"max_lanes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserRuntimeStats) Reset() {
	*x = UserRuntimeStats{}
	mi := &file_api_control_v1_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRuntimeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRuntimeStats) ProtoMessage() {}

func (x *UserRuntimeStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRuntimeStats.ProtoReflect.Descriptor instead.
func (*UserRuntimeStats) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{16}
}

func (x *UserRuntimeStats) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *UserRuntimeStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRuntimeStats) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UserRuntimeStats) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *UserRuntimeStats) GetLastSeenSinceStart() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenSinceStart
	}
	return nil
}

func (x *UserRuntimeStats) GetConnections() int32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *UserRuntimeStats) GetLanes() int32 {
	if x != nil {
		return x.Lanes
	}
	return 0
}

func (x *UserRuntimeStats) GetStreams() int32 {
	if x != nil {
		return x.Streams
	}
	return 0
}

func (x *UserRuntimeStats) GetRxBytesSinceStart() uint64 {
	if x != nil {
		return x.RxBytesSinceStart
	}
	return 0
}

func (x *UserRuntimeStats) GetTxBytesSinceStart() uint64 {
	if x != nil {
		return x.TxBytesSinceStart
	}
	return 0
}

func (x *UserRuntimeStats) GetMaxSessions() int32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

func (x *UserRuntimeStats) GetMaxLanes() int32 {
	if x != nil {
		return x.MaxLanes
	}
	return 0
}

type BoardRuntimeStats struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Tag                    string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Name                   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hash                   string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Enabled                bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	State                  string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Error                  string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	Clients                int32                  `protobuf:"varint,7,opt,name=clients,proto3" json:"clients,omitempty"`
	FreePages              int32                  `protobuf:"varint,8,opt,name=free_pages,json=freePages,proto3" json:"free_pages,omitempty"`
	RxBytes                uint64                 `protobuf:"varint,9,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes                uint64                 `protobuf:"varint,10,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	PageCleanupRuns        uint64                 `protobuf:"varint,11,opt,name=page_cleanup_runs,json=pageCleanupRuns,proto3" json:"page_cleanup_runs,omitempty"`
	PageCleanupDeleted     uint64                 `protobuf:"varint,12,opt,name=page_cleanup_deleted,json=pageCleanupDeleted,proto3" json:"page_cleanup_deleted,omitempty"`
	PageCleanupFailures    uint64                 `protobuf:"varint,13,opt,name=page_cleanup_failures,json=pageCleanupFailures,proto3" json:"page_cleanup_failures,omitempty"`
	PageCleanupQuarantined uint64                 `protobuf:"varint,14,opt,name=page_cleanup_quarantined,json=pageCleanupQuarantined,proto3" json:"page_cleanup_quarantined,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BoardRuntimeStats) Reset() {
	*x = BoardRuntimeStats{}
	mi := &file_api_control_v1_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardRuntimeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardRuntimeStats) ProtoMessage() {}

func (x *BoardRuntimeStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardRuntimeStats.ProtoReflect.Descriptor instead.
func (*BoardRuntimeStats) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{17}
}

func (x *BoardRuntimeStats) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *BoardRuntimeStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BoardRuntimeStats) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *BoardRuntimeStats) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *BoardRuntimeStats) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *BoardRuntimeStats) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BoardRuntimeStats) GetClients() int32 {
	if x != nil {
		return x.Clients
	}
	return 0
}

func (x *BoardRuntimeStats) GetFreePages() int32 {
	if x != nil {
		return x.FreePages
	}
	return 0
}

func (x *BoardRuntimeStats) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *BoardRuntimeStats) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *BoardRuntimeStats) GetPageCleanupRuns() uint64 {
	if x != nil {
		return x.PageCleanupRuns
	}
	return 0
}

func (x *BoardRuntimeStats) GetPageCleanupDeleted() uint64 {
	if x != nil {
		return x.PageCleanupDeleted
	}
	return 0
}

func (x *BoardRuntimeStats) GetPageCleanupFailures() uint64 {
	if x != nil {
		return x.PageCleanupFailures
	}
	return 0
}

func (x *BoardRuntimeStats) GetPageCleanupQuarantined() uint64 {
	if x != nil {
		return x.PageCleanupQuarantined
	}
	return 0
}

type NetworkStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Available         bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Scope             string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Interfaces        []string               `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	SampledAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=sampled_at,json=sampledAt,proto3" json:"sampled_at,omitempty"`
	RxBytesSinceStart uint64                 `protobuf:"varint,5,opt,name=rx_bytes_since_start,json=rxBytesSinceStart,proto3" json:"rx_bytes_since_start,omitempty"`
	TxBytesSinceStart uint64                 `protobuf:"varint,6,opt,name=tx_bytes_since_start,json=txBytesSinceStart,proto3" json:"tx_bytes_since_start,omitempty"`
	RxBytesPerSecond  float64                `protobuf:"fixed64,7,opt,name=rx_bytes_per_second,json=rxBytesPerSecond,proto3" json:"rx_bytes_per_second,omitempty"`
	TxBytesPerSecond  float64                `protobuf:"fixed64,8,opt,name=tx_bytes_per_second,json=txBytesPerSecond,proto3" json:"tx_bytes_per_second,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NetworkStats) Reset() {
	*x = NetworkStats{}
	mi := &file_api_control_v1_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStats) ProtoMessage() {}

func (x *NetworkStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStats.ProtoReflect.Descriptor instead.
func (*NetworkStats) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{18}
}

func (x *NetworkStats) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *NetworkStats) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *NetworkStats) GetInterfaces() []string {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *NetworkStats) GetSampledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SampledAt
	}
	return nil
}

func (x *NetworkStats) GetRxBytesSinceStart() uint64 {
	if x != nil {
		return x.RxBytesSinceStart
	}
	return 0
}

func (x *NetworkStats) GetTxBytesSinceStart() uint64 {
	if x != nil {
		return x.TxBytesSinceStart
	}
	return 0
}

func (x *NetworkStats) GetRxBytesPerSecond() float64 {
	if x != nil {
		return x.RxBytesPerSecond
	}
	return 0
}

func (x *NetworkStats) GetTxBytesPerSecond() float64 {
	if x != nil {
		return x.TxBytesPerSecond
	}
	return 0
}

type TransportStats struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	DisconnectsTotal        uint64                 `protobuf:"varint,1,opt,name=disconnects_total,json=disconnectsTotal,proto3" json:"disconnects_total,omitempty"`
	ReconnectsTotal         uint64                 `protobuf:"varint,2,opt,name=reconnects_total,json=reconnectsTotal,proto3" json:"reconnects_total,omitempty"`
	ReconnectAttemptsFailed uint64                 `protobuf:"varint,3,opt,name=reconnect_attempts_failed,json=reconnectAttemptsFailed,proto3" json:"reconnect_attempts_failed,omitempty"`
	CircuitOpenTotal        uint64                 `protobuf:"varint,4,opt,name=circuit_open_total,json=circuitOpenTotal,proto3" json:"circuit_open_total,omitempty"`
	SnapshotObjectsTotal    uint64                 `protobuf:"varint,5,opt,name=snapshot_objects_total,json=snapshotObjectsTotal,proto3" json:"snapshot_objects_total,omitempty"`
	SnapshotBytesTotal      uint64                 `protobuf:"varint,6,opt,name=snapshot_bytes_total,json=snapshotBytesTotal,proto3" json:"snapshot_bytes_total,omitempty"`
	ReconnectsLastMinute    int32                  `protobuf:"varint,7,opt,name=reconnects_last_minute,json=reconnectsLastMinute,proto3" json:"reconnects_last_minute,omitempty"`
	SnapshotBytesLastMinute uint64                 `protobuf:"varint,8,opt,name=snapshot_bytes_last_minute,json=snapshotBytesLastMinute,proto3" json:"snapshot_bytes_last_minute,omitempty"`
	LastDisconnectAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_disconnect_at,json=lastDisconnectAt,proto3" json:"last_disconnect_at,omitempty"`
	LastDisconnectReason    string                 `protobuf:"bytes,10,opt,name=last_disconnect_reason,json=lastDisconnectReason,proto3" json:"last_disconnect_reason,omitempty"`
	LastReconnectAt         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_reconnect_at,json=lastReconnectAt,proto3" json:"last_reconnect_at,omitempty"`
	LastDowntimeMs          int64                  `protobuf:"varint,12,opt,name=last_downtime_ms,json=lastDowntimeMs,proto3" json:"last_downtime_ms,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TransportStats) Reset() {
	*x = TransportStats{}
	mi := &file_api_control_v1_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportStats) ProtoMessage() {}

func (x *TransportStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportStats.ProtoReflect.Descriptor instead.
func (*TransportStats) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{19}
}

func (x *TransportStats) GetDisconnectsTotal() uint64 {
	if x != nil {
		return x.DisconnectsTotal
	}
	return 0
}

func (x *TransportStats) GetReconnectsTotal() uint64 {
	if x != nil {
		return x.ReconnectsTotal
	}
	return 0
}

func (x *TransportStats) GetReconnectAttemptsFailed() uint64 {
	if x != nil {
		return x.ReconnectAttemptsFailed
	}
	return 0
}

func (x *TransportStats) GetCircuitOpenTotal() uint64 {
	if x != nil {
		return x.CircuitOpenTotal
	}
	return 0
}

func (x *TransportStats) GetSnapshotObjectsTotal() uint64 {
	if x != nil {
		return x.SnapshotObjectsTotal
	}
	return 0
}

func (x *TransportStats) GetSnapshotBytesTotal() uint64 {
	if x != nil {
		return x.SnapshotBytesTotal
	}
	return 0
}

func (x *TransportStats) GetReconnectsLastMinute() int32 {
	if x != nil {
		return x.ReconnectsLastMinute
	}
	return 0
}

func (x *TransportStats) GetSnapshotBytesLastMinute() uint64 {
	if x != nil {
		return x.SnapshotBytesLastMinute
	}
	return 0
}

func (x *TransportStats) GetLastDisconnectAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastDisconnectAt
	}
	return nil
}

func (x *TransportStats) GetLastDisconnectReason() string {
	if x != nil {
		return x.LastDisconnectReason
	}
	return ""
}

func (x *TransportStats) GetLastReconnectAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReconnectAt
	}
	return nil
}

func (x *TransportStats) GetLastDowntimeMs() int64 {
	if x != nil {
		return x.LastDowntimeMs
	}
	return 0
}

var File_api_control_v1_control_proto protoreflect.FileDescriptor

const file_api_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x1capi/control/v1/control.proto\x12\x11bproxy.control.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n" +
	"\vRuntimeInfo\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x12#\n" +
	"\rconfig_source\x18\x02 \x01(\tR\fconfigSource\x12*\n" +
	"\x11server_public_key\x18\x03 \x01(\tR\x0fserverPublicKey\">\n" +
	"\x0fRevisionRequest\x12+\n" +
	"\x11expected_revision\x18\x01 \x01(\x04R\x10expectedRevision\"P\n" +
	"\x0fResourceRequest\x12+\n" +
	"\x11expected_revision\x18\x01 \x01(\x04R\x10expectedRevision\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\",\n" +
	"\x0eMutationResult\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\"l\n" +
	"\x11SetEnabledRequest\x12+\n" +
	"\x11expected_revision\x18\x01 \x01(\x04R\x10expectedRevision\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\"\xf3\x01\n" +
	"\bUserSpec\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12\x1d\n" +
	"\aenabled\x18\x05 \x01(\bH\x00R\aenabled\x88\x01\x01\x12\x16\n" +
	"\x06boards\x18\x06 \x03(\tR\x06boards\x12!\n" +
	"\fmax_sessions\x18\a \x01(\x05R\vmaxSessions\x12\x1b\n" +
	"\tmax_lanes\x18\b \x01(\x05R\bmaxLanesB\n" +
	"\n" +
	"\b_enabled\"r\n" +
	"\x12ReplaceUserRequest\x12+\n" +
	"\x11expected_revision\x18\x01 \x01(\x04R\x10expectedRevision\x12/\n" +
	"\x04user\x18\x02 \x01(\v2\x1b.bproxy.control.v1.UserSpecR\x04user\"\xac\x01\n" +
	"\x14ApplySnapshotRequest\x12+\n" +
	"\x11expected_revision\x18\x01 \x01(\x04R\x10expectedRevision\x121\n" +
	"\x05users\x18\x02 \x03(\v2\x1b.bproxy.control.v1.UserSpecR\x05users\x124\n" +
	"\x06boards\x18\x03 \x03(\v2\x1c.bproxy.control.v1.BoardSpecR\x06boards\"\x9b\x03\n" +
	"\bUserInfo\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x16\n" +
	"\x06boards\x18\x05 \x03(\tR\x06boards\x12!\n" +
	"\fmax_sessions\x18\x06 \x01(\x05R\vmaxSessions\x12\x1b\n" +
	"\tmax_lanes\x18\a \x01(\x05R\bmaxLanes\x12'\n" +
	"\x0factive_sessions\x18\b \x01(\x05R\x0eactiveSessions\x12/\n" +
	"\x14rx_bytes_since_start\x18\t \x01(\x04R\x11rxBytesSinceStart\x12/\n" +
	"\x14tx_bytes_since_start\x18\n" +
	" \x01(\x04R\x11txBytesSinceStart\x12M\n" +
	"\x15last_seen_since_start\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x12lastSeenSinceStart\"b\n" +
	"\x11ListUsersResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x121\n" +
	"\x05users\x18\x02 \x03(\v2\x1b.bproxy.control.v1.UserInfoR\x05users\"+\n" +
	"\x0fKeylinkResponse\x12\x18\n" +
	"\akeylink\x18\x01 \x01(\tR\akeylink\"\xe4\x01\n" +
	"\tBoardSpec\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x1b\n" +
	"\thub_slide\x18\x04 \x01(\tR\bhubSlide\x12\x19\n" +
	"\bapi_base\x18\x05 \x01(\tR\aapiBase\x12\x1d\n" +
	"\n" +
	"guest_name\x18\x06 \x01(\tR\tguestName\x12\x1d\n" +
	"\aenabled\x18\a \x01(\bH\x00R\aenabled\x88\x01\x01\x12\x1b\n" +
	"\tmax_lanes\x18\b \x01(\x05R\bmaxLanesB\n" +
	"\n" +
	"\b_enabled\"v\n" +
	"\x13ReplaceBoardRequest\x12+\n" +
	"\x11expected_revision\x18\x01 \x01(\x04R\x10expectedRevision\x122\n" +
	"\x05board\x18\x02 \x01(\v2\x1c.bproxy.control.v1.BoardSpecR\x05board\"m\n" +
	"\tBoardInfo\x124\n" +
	"\x06config\x18\x01 \x01(\v2\x1c.bproxy.control.v1.BoardSpecR\x06config\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"f\n" +
	"\x12ListBoardsResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x124\n" +
	"\x06boards\x18\x02 \x03(\v2\x1c.bproxy.control.v1.BoardInfoR\x06boards\"\xa3\x06\n" +
	"\fRuntimeStats\x129\n" +
	"\n" +
	"started_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12)\n" +
	"\x10users_configured\x18\x03 \x01(\x05R\x0fusersConfigured\x12#\n" +
	"\rusers_enabled\x18\x04 \x01(\x05R\fusersEnabled\x12!\n" +
	"\fusers_online\x18\x05 \x01(\x05R\vusersOnline\x12+\n" +
	"\x11boards_configured\x18\x06 \x01(\x05R\x10boardsConfigured\x12%\n" +
	"\x0eboards_enabled\x18\a \x01(\x05R\rboardsEnabled\x12%\n" +
	"\x0eboards_running\x18\b \x01(\x05R\rboardsRunning\x12-\n" +
	"\x12active_connections\x18\t \x01(\x05R\x11activeConnections\x12!\n" +
	"\factive_lanes\x18\n" +
	" \x01(\x05R\vactiveLanes\x12%\n" +
	"\x0eactive_streams\x18\v \x01(\x05R\ractiveStreams\x12/\n" +
	"\x14rx_bytes_since_start\x18\f \x01(\x04R\x11rxBytesSinceStart\x12/\n" +
	"\x14tx_bytes_since_start\x18\r \x01(\x04R\x11txBytesSinceStart\x129\n" +
	"\x05users\x18\x0e \x03(\v2#.bproxy.control.v1.UserRuntimeStatsR\x05users\x12<\n" +
	"\x06boards\x18\x0f \x03(\v2$.bproxy.control.v1.BoardRuntimeStatsR\x06boards\x129\n" +
	"\anetwork\x18\x10 \x01(\v2\x1f.bproxy.control.v1.NetworkStatsR\anetwork\x12?\n" +
	"\ttransport\x18\x11 \x01(\v2!.bproxy.control.v1.TransportStatsR\ttransport\"\xad\x03\n" +
	"\x10UserRuntimeStats\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x16\n" +
	"\x06online\x18\x04 \x01(\bR\x06online\x12M\n" +
	"\x15last_seen_since_start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x12lastSeenSinceStart\x12 \n" +
	"\vconnections\x18\x06 \x01(\x05R\vconnections\x12\x14\n" +
	"\x05lanes\x18\a \x01(\x05R\x05lanes\x12\x18\n" +
	"\astreams\x18\b \x01(\x05R\astreams\x12/\n" +
	"\x14rx_bytes_since_start\x18\t \x01(\x04R\x11rxBytesSinceStart\x12/\n" +
	"\x14tx_bytes_since_start\x18\n" +
	" \x01(\x04R\x11txBytesSinceStart\x12!\n" +
	"\fmax_sessions\x18\v \x01(\x05R\vmaxSessions\x12\x1b\n" +
	"\tmax_lanes\x18\f \x01(\x05R\bmaxLanes\"\xce\x03\n" +
	"\x11BoardRuntimeStats\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x18\n" +
	"\aclients\x18\a \x01(\x05R\aclients\x12\x1d\n" +
	"\n" +
	"free_pages\x18\b \x01(\x05R\tfreePages\x12\x19\n" +
	"\brx_bytes\x18\t \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\n" +
	" \x01(\x04R\atxBytes\x12*\n" +
	"\x11page_cleanup_runs\x18\v \x01(\x04R\x0fpageCleanupRuns\x120\n" +
	"\x14page_cleanup_deleted\x18\f \x01(\x04R\x12pageCleanupDeleted\x122\n" +
	"\x15page_cleanup_failures\x18\r \x01(\x04R\x13pageCleanupFailures\x128\n" +
	"\x18page_cleanup_quarantined\x18\x0e \x01(\x04R\x16pageCleanupQuarantined\"\xdd\x02\n" +
	"\fNetworkStats\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x1e\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\tR\n" +
	"interfaces\x129\n" +
	"\n" +
	"sampled_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tsampledAt\x12/\n" +
	"\x14rx_bytes_since_start\x18\x05 \x01(\x04R\x11rxBytesSinceStart\x12/\n" +
	"\x14tx_bytes_since_start\x18\x06 \x01(\x04R\x11txBytesSinceStart\x12-\n" +
	"\x13rx_bytes_per_second\x18\a \x01(\x01R\x10rxBytesPerSecond\x12-\n" +
	"\x13tx_bytes_per_second\x18\b \x01(\x01R\x10txBytesPerSecond\"\x9f\x05\n" +
	"\x0eTransportStats\x12+\n" +
	"\x11disconnects_total\x18\x01 \x01(\x04R\x10disconnectsTotal\x12)\n" +
	"\x10reconnects_total\x18\x02 \x01(\x04R\x0freconnectsTotal\x12:\n" +
	"\x19reconnect_attempts_failed\x18\x03 \x01(\x04R\x17reconnectAttemptsFailed\x12,\n" +
	"\x12circuit_open_total\x18\x04 \x01(\x04R\x10circuitOpenTotal\x124\n" +
	"\x16snapshot_objects_total\x18\x05 \x01(\x04R\x14snapshotObjectsTotal\x120\n" +
	"\x14snapshot_bytes_total\x18\x06 \x01(\x04R\x12snapshotBytesTotal\x124\n" +
	"\x16reconnects_last_minute\x18\a \x01(\x05R\x14reconnectsLastMinute\x12;\n" +
	"\x1asnapshot_bytes_last_minute\x18\b \x01(\x04R\x17snapshotBytesLastMinute\x12H\n" +
	"\x12last_disconnect_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x10lastDisconnectAt\x124\n" +
	"\x16last_disconnect_reason\x18\n" +
	" \x01(\tR\x14lastDisconnectReason\x12F\n" +
	"\x11last_reconnect_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0flastReconnectAt\x12(\n" +
	"\x10last_downtime_ms\x18\f \x01(\x03R\x0elastDowntimeMs2\xcd\b\n" +
	"\x0eControlService\x12D\n" +
	"\n" +
	"GetRuntime\x12\x16.google.protobuf.Empty\x1a\x1e.bproxy.control.v1.RuntimeInfo\x12O\n" +
	"\x06Reload\x12\".bproxy.control.v1.RevisionRequest\x1a!.bproxy.control.v1.MutationResult\x12[\n" +
	"\rApplySnapshot\x12'.bproxy.control.v1.ApplySnapshotRequest\x1a!.bproxy.control.v1.MutationResult\x12I\n" +
	"\tListUsers\x12\x16.google.protobuf.Empty\x1a$.bproxy.control.v1.ListUsersResponse\x12W\n" +
	"\vReplaceUser\x12%.bproxy.control.v1.ReplaceUserRequest\x1a!.bproxy.control.v1.MutationResult\x12Y\n" +
	"\x0eSetUserEnabled\x12$.bproxy.control.v1.SetEnabledRequest\x1a!.bproxy.control.v1.MutationResult\x12S\n" +
	"\n" +
	"RemoveUser\x12\".bproxy.control.v1.ResourceRequest\x1a!.bproxy.control.v1.MutationResult\x12T\n" +
	"\n" +
	"GetKeylink\x12\".bproxy.control.v1.ResourceRequest\x1a\".bproxy.control.v1.KeylinkResponse\x12K\n" +
	"\n" +
	"ListBoards\x12\x16.google.protobuf.Empty\x1a%.bproxy.control.v1.ListBoardsResponse\x12Y\n" +
	"\fReplaceBoard\x12&.bproxy.control.v1.ReplaceBoardRequest\x1a!.bproxy.control.v1.MutationResult\x12Z\n" +
	"\x0fSetBoardEnabled\x12$.bproxy.control.v1.SetEnabledRequest\x1a!.bproxy.control.v1.MutationResult\x12T\n" +
	"\vRemoveBoard\x12\".bproxy.control.v1.ResourceRequest\x1a!.bproxy.control.v1.MutationResult\x12C\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a\x1f.bproxy.control.v1.RuntimeStatsB&Z$bproxy-core/api/control/v1;controlv1b\x06proto3"

var (
	file_api_control_v1_control_proto_rawDescOnce sync.Once
	file_api_control_v1_control_proto_rawDescData []byte
)

func file_api_control_v1_control_proto_rawDescGZIP() []byte {
	file_api_control_v1_control_proto_rawDescOnce.Do(func() {
		file_api_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_control_v1_control_proto_rawDesc), len(file_api_control_v1_control_proto_rawDesc)))
	})
	return file_api_control_v1_control_proto_rawDescData
}

var file_api_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_control_v1_control_proto_goTypes = []any{
	(*RuntimeInfo)(nil),           // 0: bproxy.control.v1.RuntimeInfo
	(*RevisionRequest)(nil),       // 1: bproxy.control.v1.RevisionRequest
	(*ResourceRequest)(nil),       // 2: bproxy.control.v1.ResourceRequest
	(*MutationResult)(nil),        // 3: bproxy.control.v1.MutationResult
	(*SetEnabledRequest)(nil),     // 4: bproxy.control.v1.SetEnabledRequest
	(*UserSpec)(nil),              // 5: bproxy.control.v1.UserSpec
	(*ReplaceUserRequest)(nil),    // 6: bproxy.control.v1.ReplaceUserRequest
	(*ApplySnapshotRequest)(nil),  // 7: bproxy.control.v1.ApplySnapshotRequest
	(*UserInfo)(nil),              // 8: bproxy.control.v1.UserInfo
	(*ListUsersResponse)(nil),     // 9: bproxy.control.v1.ListUsersResponse
	(*KeylinkResponse)(nil),       // 10: bproxy.control.v1.KeylinkResponse
	(*BoardSpec)(nil),             // 11: bproxy.control.v1.BoardSpec
	(*ReplaceBoardRequest)(nil),   // 12: bproxy.control.v1.ReplaceBoardRequest
	(*BoardInfo)(nil),             // 13: bproxy.control.v1.BoardInfo
	(*ListBoardsResponse)(nil),    // 14: bproxy.control.v1.ListBoardsResponse
	(*RuntimeStats)(nil),          // 15: bproxy.control.v1.RuntimeStats
	(*UserRuntimeStats)(nil),      // 16: bproxy.control.v1.UserRuntimeStats
	(*BoardRuntimeStats)(nil),     // 17: bproxy.control.v1.BoardRuntimeStats
	(*NetworkStats)(nil),          // 18: bproxy.control.v1.NetworkStats
	(*TransportStats)(nil),        // 19: bproxy.control.v1.TransportStats
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 21: google.protobuf.Empty
}
var file_api_control_v1_control_proto_depIdxs = []int32{
	5,  // 0: bproxy.control.v1.ReplaceUserRequest.user:type_name -> bproxy.control.v1.UserSpec
	5,  // 1: bproxy.control.v1.ApplySnapshotRequest.users:type_name -> bproxy.control.v1.UserSpec
	11, // 2: bproxy.control.v1.ApplySnapshotRequest.boards:type_name -> bproxy.control.v1.BoardSpec
	20, // 3: bproxy.control.v1.UserInfo.last_seen_since_start:type_name -> google.protobuf.Timestamp
	8,  // 4: bproxy.control.v1.ListUsersResponse.users:type_name -> bproxy.control.v1.UserInfo
	11, // 5: bproxy.control.v1.ReplaceBoardRequest.board:type_name -> bproxy.control.v1.BoardSpec
	11, // 6: bproxy.control.v1.BoardInfo.config:type_name -> bproxy.control.v1.BoardSpec
	13, // 7: bproxy.control.v1.ListBoardsResponse.boards:type_name -> bproxy.control.v1.BoardInfo
	20, // 8: bproxy.control.v1.RuntimeStats.started_at:type_name -> google.protobuf.Timestamp
	16, // 9: bproxy.control.v1.RuntimeStats.users:type_name -> bproxy.control.v1.UserRuntimeStats
	17, // 10: bproxy.control.v1.RuntimeStats.boards:type_name -> bproxy.control.v1.BoardRuntimeStats
	18, // 11: bproxy.control.v1.RuntimeStats.network:type_name -> bproxy.control.v1.NetworkStats
	19, // 12: bproxy.control.v1.RuntimeStats.transport:type_name -> bproxy.control.v1.TransportStats
	20, // 13: bproxy.control.v1.UserRuntimeStats.last_seen_since_start:type_name -> google.protobuf.Timestamp
	20, // 14: bproxy.control.v1.NetworkStats.sampled_at:type_name -> google.protobuf.Timestamp
	20, // 15: bproxy.control.v1.TransportStats.last_disconnect_at:type_name -> google.protobuf.Timestamp
	20, // 16: bproxy.control.v1.TransportStats.last_reconnect_at:type_name -> google.protobuf.Timestamp
	21, // 17: bproxy.control.v1.ControlService.GetRuntime:input_type -> google.protobuf.Empty
	1,  // 18: bproxy.control.v1.ControlService.Reload:input_type -> bproxy.control.v1.RevisionRequest
	7,  // 19: bproxy.control.v1.ControlService.ApplySnapshot:input_type -> bproxy.control.v1.ApplySnapshotRequest
	21, // 20: bproxy.control.v1.ControlService.ListUsers:input_type -> google.protobuf.Empty
	6,  // 21: bproxy.control.v1.ControlService.ReplaceUser:input_type -> bproxy.control.v1.ReplaceUserRequest
	4,  // 22: bproxy.control.v1.ControlService.SetUserEnabled:input_type -> bproxy.control.v1.SetEnabledRequest
	2,  // 23: bproxy.control.v1.ControlService.RemoveUser:input_type -> bproxy.control.v1.ResourceRequest
	2,  // 24: bproxy.control.v1.ControlService.GetKeylink:input_type -> bproxy.control.v1.ResourceRequest
	21, // 25: bproxy.control.v1.ControlService.ListBoards:input_type -> google.protobuf.Empty
	12, // 26: bproxy.control.v1.ControlService.ReplaceBoard:input_type -> bproxy.control.v1.ReplaceBoardRequest
	4,  // 27: bproxy.control.v1.ControlService.SetBoardEnabled:input_type -> bproxy.control.v1.SetEnabledRequest
	2,  // 28: bproxy.control.v1.ControlService.RemoveBoard:input_type -> bproxy.control.v1.ResourceRequest
	21, // 29: bproxy.control.v1.ControlService.GetStats:input_type -> google.protobuf.Empty
	0,  // 30: bproxy.control.v1.ControlService.GetRuntime:output_type -> bproxy.control.v1.RuntimeInfo
	3,  // 31: bproxy.control.v1.ControlService.Reload:output_type -> bproxy.control.v1.MutationResult
	3,  // 32: bproxy.control.v1.ControlService.ApplySnapshot:output_type -> bproxy.control.v1.MutationResult
	9,  // 33: bproxy.control.v1.ControlService.ListUsers:output_type -> bproxy.control.v1.ListUsersResponse
	3,  // 34: bproxy.control.v1.ControlService.ReplaceUser:output_type -> bproxy.control.v1.MutationResult
	3,  // 35: bproxy.control.v1.ControlService.SetUserEnabled:output_type -> bproxy.control.v1.MutationResult
	3,  // 36: bproxy.control.v1.ControlService.RemoveUser:output_type -> bproxy.control.v1.MutationResult
	10, // 37: bproxy.control.v1.ControlService.GetKeylink:output_type -> bproxy.control.v1.KeylinkResponse
	14, // 38: bproxy.control.v1.ControlService.ListBoards:output_type -> bproxy.control.v1.ListBoardsResponse
	3,  // 39: bproxy.control.v1.ControlService.ReplaceBoard:output_type -> bproxy.control.v1.MutationResult
	3,  // 40: bproxy.control.v1.ControlService.SetBoardEnabled:output_type -> bproxy.control.v1.MutationResult
	3,  // 41: bproxy.control.v1.ControlService.RemoveBoard:output_type -> bproxy.control.v1.MutationResult
	15, // 42: bproxy.control.v1.ControlService.GetStats:output_type -> bproxy.control.v1.RuntimeStats
	30, // [30:43] is the sub-list for method output_type
	17, // [17:30] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_api_control_v1_control_proto_init() }
func file_api_control_v1_control_proto_init() {
	if File_api_control_v1_control_proto != nil {
		return
	}
	file_api_control_v1_control_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_control_v1_control_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_control_v1_control_proto_rawDesc), len(file_api_control_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_control_v1_control_proto_goTypes,
		DependencyIndexes: file_api_control_v1_control_proto_depIdxs,
		MessageInfos:      file_api_control_v1_control_proto_msgTypes,
	}.Build()
	File_api_control_v1_control_proto = out.File
	file_api_control_v1_control_proto_goTypes = nil
	file_api_control_v1_control_proto_depIdxs = nil
}
