// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: api/control/v1/control.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlService_GetRuntime_FullMethodName      = "/bproxy.control.v1.ControlService/GetRuntime"
	ControlService_Reload_FullMethodName          = "/bproxy.control.v1.ControlService/Reload"
	ControlService_ApplySnapshot_FullMethodName   = "/bproxy.control.v1.ControlService/ApplySnapshot"
	ControlService_ListUsers_FullMethodName       = "/bproxy.control.v1.ControlService/ListUsers"
	ControlService_AddUser_FullMethodName         = "/bproxy.control.v1.ControlService/AddUser"
	ControlService_ReplaceUser_FullMethodName     = "/bproxy.control.v1.ControlService/ReplaceUser"
	ControlService_SetUserEnabled_FullMethodName  = "/bproxy.control.v1.ControlService/SetUserEnabled"
	ControlService_RemoveUser_FullMethodName      = "/bproxy.control.v1.ControlService/RemoveUser"
	ControlService_GetKeylink_FullMethodName      = "/bproxy.control.v1.ControlService/GetKeylink"
	ControlService_ListBoards_FullMethodName      = "/bproxy.control.v1.ControlService/ListBoards"
	ControlService_AddBoard_FullMethodName        = "/bproxy.control.v1.ControlService/AddBoard"
	ControlService_ReplaceBoard_FullMethodName    = "/bproxy.control.v1.ControlService/ReplaceBoard"
	ControlService_SetBoardEnabled_FullMethodName = "/bproxy.control.v1.ControlService/SetBoardEnabled"
	ControlService_RemoveBoard_FullMethodName     = "/bproxy.control.v1.ControlService/RemoveBoard"
	ControlService_GetStats_FullMethodName        = "/bproxy.control.v1.ControlService/GetStats"
)

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlServiceClient interface {
	GetRuntime(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RuntimeInfo, error)
	Reload(ctx context.Context, in *RevisionRequest, opts ...grpc.CallOption) (*MutationResult, error)
	// Atomically replaces the complete runtime user/board desired-state slice.
	// Server identity, transport and listener settings remain file-owned.
	ApplySnapshot(ctx context.Context, in *ApplySnapshotRequest, opts ...grpc.CallOption) (*MutationResult, error)
	ListUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListUsersResponse, error)
	// Creates a missing user and fails with ALREADY_EXISTS for an existing tag.
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*MutationResult, error)
	ReplaceUser(ctx context.Context, in *ReplaceUserRequest, opts ...grpc.CallOption) (*MutationResult, error)
	SetUserEnabled(ctx context.Context, in *SetEnabledRequest, opts ...grpc.CallOption) (*MutationResult, error)
	RemoveUser(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*MutationResult, error)
	GetKeylink(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*KeylinkResponse, error)
	ListBoards(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListBoardsResponse, error)
	// Creates a missing board and fails with ALREADY_EXISTS for an existing tag.
	AddBoard(ctx context.Context, in *AddBoardRequest, opts ...grpc.CallOption) (*MutationResult, error)
	ReplaceBoard(ctx context.Context, in *ReplaceBoardRequest, opts ...grpc.CallOption) (*MutationResult, error)
	SetBoardEnabled(ctx context.Context, in *SetEnabledRequest, opts ...grpc.CallOption) (*MutationResult, error)
	RemoveBoard(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*MutationResult, error)
	GetStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RuntimeStats, error)
}

type controlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlServiceClient(cc grpc.ClientConnInterface) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) GetRuntime(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RuntimeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeInfo)
	err := c.cc.Invoke(ctx, ControlService_GetRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Reload(ctx context.Context, in *RevisionRequest, opts ...grpc.CallOption) (*MutationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationResult)
	err := c.cc.Invoke(ctx, ControlService_Reload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ApplySnapshot(ctx context.Context, in *ApplySnapshotRequest, opts ...grpc.CallOption) (*MutationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationResult)
	err := c.cc.Invoke(ctx, ControlService_ApplySnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, ControlService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*MutationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationResult)
	err := c.cc.Invoke(ctx, ControlService_AddUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ReplaceUser(ctx context.Context, in *ReplaceUserRequest, opts ...grpc.CallOption) (*MutationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationResult)
	err := c.cc.Invoke(ctx, ControlService_ReplaceUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SetUserEnabled(ctx context.Context, in *SetEnabledRequest, opts ...grpc.CallOption) (*MutationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationResult)
	err := c.cc.Invoke(ctx, ControlService_SetUserEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) RemoveUser(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*MutationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationResult)
	err := c.cc.Invoke(ctx, ControlService_RemoveUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetKeylink(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*KeylinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeylinkResponse)
	err := c.cc.Invoke(ctx, ControlService_GetKeylink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListBoards(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListBoardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBoardsResponse)
	err := c.cc.Invoke(ctx, ControlService_ListBoards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) AddBoard(ctx context.Context, in *AddBoardRequest, opts ...grpc.CallOption) (*MutationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationResult)
	err := c.cc.Invoke(ctx, ControlService_AddBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ReplaceBoard(ctx context.Context, in *ReplaceBoardRequest, opts ...grpc.CallOption) (*MutationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationResult)
	err := c.cc.Invoke(ctx, ControlService_ReplaceBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SetBoardEnabled(ctx context.Context, in *SetEnabledRequest, opts ...grpc.CallOption) (*MutationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationResult)
	err := c.cc.Invoke(ctx, ControlService_SetBoardEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) RemoveBoard(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*MutationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationResult)
	err := c.cc.Invoke(ctx, ControlService_RemoveBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RuntimeStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeStats)
	err := c.cc.Invoke(ctx, ControlService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServiceServer is the server API for ControlService service.
// All implementations must embed UnimplementedControlServiceServer
// for forward compatibility.
type ControlServiceServer interface {
	GetRuntime(context.Context, *emptypb.Empty) (*RuntimeInfo, error)
	Reload(context.Context, *RevisionRequest) (*MutationResult, error)
	// Atomically replaces the complete runtime user/board desired-state slice.
	// Server identity, transport and listener settings remain file-owned.
	ApplySnapshot(context.Context, *ApplySnapshotRequest) (*MutationResult, error)
	ListUsers(context.Context, *emptypb.Empty) (*ListUsersResponse, error)
	// Creates a missing user and fails with ALREADY_EXISTS for an existing tag.
	AddUser(context.Context, *AddUserRequest) (*MutationResult, error)
	ReplaceUser(context.Context, *ReplaceUserRequest) (*MutationResult, error)
	SetUserEnabled(context.Context, *SetEnabledRequest) (*MutationResult, error)
	RemoveUser(context.Context, *ResourceRequest) (*MutationResult, error)
	GetKeylink(context.Context, *ResourceRequest) (*KeylinkResponse, error)
	ListBoards(context.Context, *emptypb.Empty) (*ListBoardsResponse, error)
	// Creates a missing board and fails with ALREADY_EXISTS for an existing tag.
	AddBoard(context.Context, *AddBoardRequest) (*MutationResult, error)
	ReplaceBoard(context.Context, *ReplaceBoardRequest) (*MutationResult, error)
	SetBoardEnabled(context.Context, *SetEnabledRequest) (*MutationResult, error)
	RemoveBoard(context.Context, *ResourceRequest) (*MutationResult, error)
	GetStats(context.Context, *emptypb.Empty) (*RuntimeStats, error)
	mustEmbedUnimplementedControlServiceServer()
}

// UnimplementedControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServiceServer struct{}

func (UnimplementedControlServiceServer) GetRuntime(context.Context, *emptypb.Empty) (*RuntimeInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRuntime not implemented")
}
func (UnimplementedControlServiceServer) Reload(context.Context, *RevisionRequest) (*MutationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedControlServiceServer) ApplySnapshot(context.Context, *ApplySnapshotRequest) (*MutationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplySnapshot not implemented")
}
func (UnimplementedControlServiceServer) ListUsers(context.Context, *emptypb.Empty) (*ListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedControlServiceServer) AddUser(context.Context, *AddUserRequest) (*MutationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUser not implemented")
}
func (UnimplementedControlServiceServer) ReplaceUser(context.Context, *ReplaceUserRequest) (*MutationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplaceUser not implemented")
}
func (UnimplementedControlServiceServer) SetUserEnabled(context.Context, *SetEnabledRequest) (*MutationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUserEnabled not implemented")
}
func (UnimplementedControlServiceServer) RemoveUser(context.Context, *ResourceRequest) (*MutationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveUser not implemented")
}
func (UnimplementedControlServiceServer) GetKeylink(context.Context, *ResourceRequest) (*KeylinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKeylink not implemented")
}
func (UnimplementedControlServiceServer) ListBoards(context.Context, *emptypb.Empty) (*ListBoardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBoards not implemented")
}
func (UnimplementedControlServiceServer) AddBoard(context.Context, *AddBoardRequest) (*MutationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBoard not implemented")
}
func (UnimplementedControlServiceServer) ReplaceBoard(context.Context, *ReplaceBoardRequest) (*MutationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplaceBoard not implemented")
}
func (UnimplementedControlServiceServer) SetBoardEnabled(context.Context, *SetEnabledRequest) (*MutationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBoardEnabled not implemented")
}
func (UnimplementedControlServiceServer) RemoveBoard(context.Context, *ResourceRequest) (*MutationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveBoard not implemented")
}
func (UnimplementedControlServiceServer) GetStats(context.Context, *emptypb.Empty) (*RuntimeStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedControlServiceServer) mustEmbedUnimplementedControlServiceServer() {}
func (UnimplementedControlServiceServer) testEmbeddedByValue()                        {}

// UnsafeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServiceServer will
// result in compilation errors.
type UnsafeControlServiceServer interface {
	mustEmbedUnimplementedControlServiceServer()
}

func RegisterControlServiceServer(s grpc.ServiceRegistrar, srv ControlServiceServer) {
	// If the following call panics, it indicates UnimplementedControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlService_ServiceDesc, srv)
}

func _ControlService_GetRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetRuntime(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Reload(ctx, req.(*RevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ApplySnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplySnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ApplySnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ApplySnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ApplySnapshot(ctx, req.(*ApplySnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListUsers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_AddUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ReplaceUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ReplaceUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ReplaceUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ReplaceUser(ctx, req.(*ReplaceUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SetUserEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SetUserEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_SetUserEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SetUserEnabled(ctx, req.(*SetEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_RemoveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).RemoveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_RemoveUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).RemoveUser(ctx, req.(*ResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetKeylink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetKeylink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetKeylink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetKeylink(ctx, req.(*ResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListBoards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListBoards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListBoards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListBoards(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_AddBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).AddBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_AddBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).AddBoard(ctx, req.(*AddBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ReplaceBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ReplaceBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ReplaceBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ReplaceBoard(ctx, req.(*ReplaceBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SetBoardEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SetBoardEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_SetBoardEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SetBoardEnabled(ctx, req.(*SetEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_RemoveBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).RemoveBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_RemoveBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).RemoveBoard(ctx, req.(*ResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetStats(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlService_ServiceDesc is the grpc.ServiceDesc for ControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bproxy.control.v1.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRuntime",
			Handler:    _ControlService_GetRuntime_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _ControlService_Reload_Handler,
		},
		{
			MethodName: "ApplySnapshot",
			Handler:    _ControlService_ApplySnapshot_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _ControlService_ListUsers_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _ControlService_AddUser_Handler,
		},
		{
			MethodName: "ReplaceUser",
			Handler:    _ControlService_ReplaceUser_Handler,
		},
		{
			MethodName: "SetUserEnabled",
			Handler:    _ControlService_SetUserEnabled_Handler,
		},
		{
			MethodName: "RemoveUser",
			Handler:    _ControlService_RemoveUser_Handler,
		},
		{
			MethodName: "GetKeylink",
			Handler:    _ControlService_GetKeylink_Handler,
		},
		{
			MethodName: "ListBoards",
			Handler:    _ControlService_ListBoards_Handler,
		},
		{
			MethodName: "AddBoard",
			Handler:    _ControlService_AddBoard_Handler,
		},
		{
			MethodName: "ReplaceBoard",
			Handler:    _ControlService_ReplaceBoard_Handler,
		},
		{
			MethodName: "SetBoardEnabled",
			Handler:    _ControlService_SetBoardEnabled_Handler,
		},
		{
			MethodName: "RemoveBoard",
			Handler:    _ControlService_RemoveBoard_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _ControlService_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/control/v1/control.proto",
}
