// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ParseLink(arg1) {
  return window['go']['main']['App']['ParseLink'](arg1);
}

export function Reconnect(arg1) {
  return window['go']['main']['App']['Reconnect'](arg1);
}

export function SetSystemProxyEnabled(arg1) {
  return window['go']['main']['App']['SetSystemProxyEnabled'](arg1);
}

export function SyncTray(arg1) {
  return window['go']['main']['App']['SyncTray'](arg1);
}

export function UpdateBypassList(arg1) {
  return window['go']['main']['App']['UpdateBypassList'](arg1);
}
