// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:main.ConnectConfig):Promise<void>;

export function Disconnect():Promise<void>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetMetrics():Promise<main.MetricsDTO>;

export function GetStatus():Promise<string>;

export function ParseLink(arg1:string):Promise<main.LinkInfo>;

export function Reconnect(arg1:main.ConnectConfig):Promise<void>;

export function SetSystemProxyEnabled(arg1:boolean):Promise<void>;

export function SyncTray(arg1:main.TrayState):Promise<void>;

export function UpdateBypassList(arg1:Array<string>):Promise<void>;
